import type { Product } from '../types';

export const laptops: Product[] = [
  {
    slug: 'macbook-air-13-m4',
    name: 'MacBook Air 13" M4',
    brand: 'apple',
    category: 'laptops',
    price: 154999,
    condition: 'new',
    stock: 5,
    tagline: 'Thin, silent and fast — with 16GB memory as standard.',
    highlights: ['Apple M4 chip, 10-core CPU', '16GB unified memory', 'Up to 18 hours battery life'],
    description:
      'The MacBook Air with M4 is fanless, light and quick enough for school, business and creative work. It now starts with 16GB of memory and a 12MP Center Stage camera for calls.',
    specs: [
      ['Display', '13.6" Liquid Retina, 2560 × 1664'],
      ['Chip', 'Apple M4 · 10-core CPU · 8-core GPU'],
      ['Memory', '16GB unified memory'],
      ['Storage', '256GB SSD'],
      ['Camera', '12MP Center Stage'],
      ['Ports', '2 × Thunderbolt 4 · MagSafe 3 · headphone jack'],
      ['Battery', 'Up to 18 hours video playback'],
      ['Weight', '1.24 kg'],
    ],
    inBox: ['MacBook Air', '30W USB‑C power adapter', 'USB‑C to MagSafe 3 cable (2 m)'],
    warranty: '12 months Apple warranty',
    colours: [
      { name: 'Sky Blue', hex: '#b9cbd8' },
      { name: 'Midnight', hex: '#2e3641' },
      { name: 'Starlight', hex: '#e3dccf' },
      { name: 'Silver', hex: '#d8d9db' },
    ],
    options: { label: 'Storage', values: [{ name: '256GB' }, { name: '512GB', delta: 30000 }] },
    art: 'laptop',
    badges: ['pick'],
    added: '2026-03-15',
    rank: 97,
    keywords: 'apple macbook air m4 mac',
  },
  {
    slug: 'macbook-pro-14-m4',
    name: 'MacBook Pro 14" M4',
    brand: 'apple',
    category: 'laptops',
    price: 239999,
    condition: 'new',
    stock: 2,
    tagline: 'A Liquid Retina XDR display and the ports professionals need.',
    highlights: ['14.2" Liquid Retina XDR display', 'Apple M4 · 16GB · 512GB', 'Up to 24 hours battery life'],
    description:
      'MacBook Pro 14 with M4 adds a brilliant mini-LED XDR display, active cooling for sustained work, HDMI and an SD card slot — built for editors, developers and designers.',
    specs: [
      ['Display', '14.2" Liquid Retina XDR, up to 120Hz'],
      ['Chip', 'Apple M4 · 10-core CPU · 10-core GPU'],
      ['Memory', '16GB unified memory'],
      ['Storage', '512GB SSD'],
      ['Ports', '3 × Thunderbolt 4 · HDMI · SDXC · MagSafe 3 · headphone jack'],
      ['Battery', 'Up to 24 hours video playback'],
      ['Weight', '1.55 kg'],
    ],
    inBox: ['MacBook Pro', '70W USB‑C power adapter', 'USB‑C to MagSafe 3 cable (2 m)'],
    warranty: '12 months Apple warranty',
    colours: [
      { name: 'Space Black', hex: '#2b2b2d' },
      { name: 'Silver', hex: '#d8d9db' },
    ],
    art: 'laptop',
    added: '2026-03-15',
    rank: 82,
    keywords: 'apple macbook pro m4 mbp',
  },
  {
    slug: 'hp-elitebook-840-g10',
    name: 'HP EliteBook 840 G10',
    brand: 'hp',
    category: 'laptops',
    price: 139999,
    compareAt: 154999,
    condition: 'new',
    stock: 6,
    tagline: 'A secure, all-day business laptop that IT departments trust.',
    highlights: ['13th Gen Intel Core i7', '16GB DDR5 · 512GB SSD', 'Windows 11 Pro'],
    description:
      'EliteBook 840 G10 is HP’s flagship business laptop: a 14-inch WUXGA screen, strong security with HP Wolf Security, and a keyboard you can type on all day.',
    specs: [
      ['Display', '14" WUXGA (1920 × 1200) IPS anti-glare'],
      ['Processor', 'Intel Core i7-1355U (13th Gen)'],
      ['Memory', '16GB DDR5'],
      ['Storage', '512GB NVMe SSD'],
      ['OS', 'Windows 11 Pro'],
      ['Ports', '2 × Thunderbolt 4 · 2 × USB‑A · HDMI 2.1'],
      ['Weight', '1.36 kg'],
    ],
    inBox: ['Laptop', '65W USB‑C charger'],
    warranty: '12 months HP warranty',
    options: { label: 'Processor', values: [{ name: 'Core i7 · 16GB · 512GB' }, { name: 'Core i5 · 16GB · 512GB', delta: -22000 }] },
    art: 'laptop',
    badges: ['deal'],
    added: '2026-02-20',
    rank: 85,
    keywords: 'hp elitebook 840 g10 business',
  },
  {
    slug: 'hp-probook-450-g10',
    name: 'HP ProBook 450 G10',
    brand: 'hp',
    category: 'laptops',
    price: 84999,
    condition: 'new',
    stock: 9,
    tagline: 'A 15.6" workhorse with a full number pad.',
    highlights: ['13th Gen Intel Core i5', '8GB RAM · 512GB SSD', 'Full-size keyboard with number pad'],
    description: 'ProBook 450 G10 is a dependable office laptop with a large 15.6-inch screen and a numeric keypad for accounts and data work.',
    specs: [
      ['Display', '15.6" FHD IPS'],
      ['Processor', 'Intel Core i5-1335U (13th Gen)'],
      ['Memory', '8GB DDR4 (upgradeable)'],
      ['Storage', '512GB NVMe SSD'],
      ['OS', 'FreeDOS (Windows 11 available)'],
      ['Weight', '1.79 kg'],
    ],
    inBox: ['Laptop', 'Charger'],
    warranty: '12 months HP warranty',
    art: 'laptop',
    added: '2026-02-20',
    rank: 73,
    keywords: 'hp probook 450 g10',
  },
  {
    slug: 'hp-250-g10',
    name: 'HP 250 G10',
    brand: 'hp',
    category: 'laptops',
    price: 54999,
    compareAt: 59999,
    condition: 'new',
    stock: 18,
    tagline: 'The student and small-office favourite.',
    highlights: ['13th Gen Intel Core i3', '8GB RAM · 256GB SSD', '15.6" Full HD screen'],
    description: 'HP 250 G10 covers the essentials well — assignments, spreadsheets, Zoom and streaming — at a price that works for families and small offices.',
    specs: [
      ['Display', '15.6" FHD anti-glare'],
      ['Processor', 'Intel Core i3-1315U (13th Gen)'],
      ['Memory', '8GB DDR4'],
      ['Storage', '256GB NVMe SSD'],
      ['OS', 'FreeDOS (Windows 11 available)'],
    ],
    inBox: ['Laptop', 'Charger'],
    warranty: '12 months HP warranty',
    options: { label: 'Processor', values: [{ name: 'Core i3 · 8GB · 256GB' }, { name: 'Core i5 · 8GB · 512GB', delta: 12000 }] },
    art: 'laptop',
    badges: ['deal'],
    added: '2026-01-15',
    rank: 89,
    keywords: 'hp 250 g10 student laptop',
  },
  {
    slug: 'dell-latitude-5440',
    name: 'Dell Latitude 5440',
    brand: 'dell',
    category: 'laptops',
    price: 109999,
    condition: 'new',
    stock: 4,
    tagline: 'Business-grade build with the ports you actually use.',
    highlights: ['13th Gen Intel Core i5', '16GB RAM · 512GB SSD', 'Windows 11 Pro'],
    description: 'Latitude 5440 is a solid 14-inch business laptop with a comfortable keyboard, good battery life and Dell’s ProSupport-ready build.',
    specs: [
      ['Display', '14" FHD IPS'],
      ['Processor', 'Intel Core i5-1345U (13th Gen)'],
      ['Memory', '16GB DDR4'],
      ['Storage', '512GB NVMe SSD'],
      ['OS', 'Windows 11 Pro'],
      ['Ports', 'Thunderbolt 4 · USB‑C · 2 × USB‑A · HDMI · RJ45'],
    ],
    inBox: ['Laptop', '65W USB‑C charger'],
    warranty: '12 months Dell warranty',
    art: 'laptop',
    added: '2026-02-01',
    rank: 71,
    keywords: 'dell latitude 5440',
  },
  {
    slug: 'dell-inspiron-15-3520',
    name: 'Dell Inspiron 15 3520',
    brand: 'dell',
    category: 'laptops',
    price: 69999,
    condition: 'new',
    stock: 8,
    tagline: 'A smooth 120Hz screen for everyday home and school work.',
    highlights: ['12th Gen Intel Core i5', '8GB RAM · 512GB SSD', '15.6" FHD 120Hz display'],
    description: 'Inspiron 15 3520 is a well-rounded home laptop with a smooth 120Hz display, a full keyboard and fast SSD storage.',
    specs: [
      ['Display', '15.6" FHD, 120Hz'],
      ['Processor', 'Intel Core i5-1235U (12th Gen)'],
      ['Memory', '8GB DDR4'],
      ['Storage', '512GB SSD'],
      ['OS', 'Windows 11 Home'],
    ],
    inBox: ['Laptop', 'Charger'],
    warranty: '12 months Dell warranty',
    art: 'laptop',
    added: '2026-01-25',
    rank: 69,
    keywords: 'dell inspiron 15 3520',
  },
  {
    slug: 'lenovo-thinkpad-e14-gen-5',
    name: 'Lenovo ThinkPad E14 Gen 5',
    brand: 'lenovo',
    category: 'laptops',
    price: 99999,
    condition: 'new',
    stock: 5,
    tagline: 'The legendary ThinkPad keyboard, in a modern 16:10 body.',
    highlights: ['13th Gen Intel Core i5', '16GB RAM · 512GB SSD', '14" WUXGA 16:10 display'],
    description: 'ThinkPad E14 Gen 5 gives small businesses ThinkPad reliability and that famous keyboard, with a taller 16:10 screen for documents.',
    specs: [
      ['Display', '14" WUXGA (1920 × 1200) IPS'],
      ['Processor', 'Intel Core i5-1335U (13th Gen)'],
      ['Memory', '16GB DDR4'],
      ['Storage', '512GB NVMe SSD'],
      ['OS', 'FreeDOS (Windows 11 available)'],
    ],
    inBox: ['Laptop', '65W USB‑C charger'],
    warranty: '12 months Lenovo warranty',
    art: 'laptop',
    added: '2026-02-10',
    rank: 67,
    keywords: 'lenovo thinkpad e14 gen 5',
  },
  {
    slug: 'asus-vivobook-15',
    name: 'ASUS Vivobook 15',
    brand: 'asus',
    category: 'laptops',
    price: 62999,
    condition: 'new',
    stock: 10,
    tagline: 'Light, modern and good value for students.',
    highlights: ['13th Gen Intel Core i5', '8GB RAM · 512GB SSD', '180° lay-flat hinge'],
    description: 'Vivobook 15 is a slim everyday laptop with a lay-flat hinge, a webcam privacy shield and a Full HD screen.',
    specs: [
      ['Display', '15.6" FHD'],
      ['Processor', 'Intel Core i5-1335U (13th Gen)'],
      ['Memory', '8GB'],
      ['Storage', '512GB SSD'],
      ['OS', 'Windows 11 Home'],
    ],
    inBox: ['Laptop', 'Charger'],
    warranty: '12 months ASUS warranty',
    colours: [
      { name: 'Quiet Blue', hex: '#3b4a63' },
      { name: 'Cool Silver', hex: '#c9cbce' },
    ],
    art: 'laptop',
    added: '2026-02-12',
    rank: 65,
    keywords: 'asus vivobook 15',
  },
  {
    slug: 'asus-rog-strix-g16',
    name: 'ASUS ROG Strix G16',
    brand: 'asus',
    category: 'laptops',
    price: 219999,
    compareAt: 239999,
    condition: 'new',
    stock: 2,
    tagline: 'RTX 4060 gaming with a 165Hz screen.',
    highlights: ['Intel Core i7-13650HX', 'NVIDIA GeForce RTX 4060', '16" 165Hz display'],
    description: 'ROG Strix G16 is a serious gaming and rendering laptop: an HX-class Core i7, RTX 4060 graphics and a fast 165Hz screen.',
    specs: [
      ['Display', '16" FHD+ 165Hz'],
      ['Processor', 'Intel Core i7-13650HX'],
      ['Graphics', 'NVIDIA GeForce RTX 4060 8GB'],
      ['Memory', '16GB DDR5'],
      ['Storage', '1TB NVMe SSD'],
      ['OS', 'Windows 11 Home'],
    ],
    inBox: ['Laptop', '240W charger'],
    warranty: '12 months ASUS warranty',
    art: 'laptop',
    badges: ['deal'],
    added: '2026-02-28',
    rank: 78,
    keywords: 'asus rog strix g16 gaming laptop rtx',
  },
  {
    slug: 'hp-elitebook-840-g5-ex-uk',
    name: 'HP EliteBook 840 G5 (ex-UK)',
    brand: 'hp',
    category: 'laptops',
    price: 32999,
    condition: 'ex-uk',
    stock: 15,
    tagline: 'A tested business laptop for the price of a budget one.',
    highlights: ['Intel Core i5 (8th Gen)', '8GB RAM · 256GB SSD', '6-month Steff Store warranty'],
    description:
      'Imported ex-UK corporate stock, graded A, fully tested and cleaned. The EliteBook 840 G5 is aluminium-built, light and still very capable for office work and study.',
    specs: [
      ['Display', '14" FHD'],
      ['Processor', 'Intel Core i5-8350U (8th Gen)'],
      ['Memory', '8GB DDR4'],
      ['Storage', '256GB SSD'],
      ['OS', 'Windows 10 Pro (Windows 11 eligible on request)'],
      ['Grade', 'A — minimal signs of use'],
    ],
    inBox: ['Laptop', 'Charger'],
    warranty: '6 months Steff Store warranty',
    options: { label: 'Memory', values: [{ name: '8GB · 256GB' }, { name: '16GB · 512GB', delta: 7000 }] },
    art: 'laptop',
    badges: ['ex-uk', 'pick'],
    added: '2026-03-05',
    rank: 91,
    keywords: 'hp elitebook 840 g5 ex uk refurbished used',
  },
  {
    slug: 'dell-latitude-7490-ex-uk',
    name: 'Dell Latitude 7490 (ex-UK)',
    brand: 'dell',
    category: 'laptops',
    price: 39999,
    condition: 'ex-uk',
    stock: 8,
    tagline: 'Core i7 and 16GB, tested and ready.',
    highlights: ['Intel Core i7 (8th Gen)', '16GB RAM · 512GB SSD', '6-month Steff Store warranty'],
    description: 'Ex-UK Latitude 7490, graded A and tested on every port and key. A premium business laptop at a fraction of its new price.',
    specs: [
      ['Display', '14" FHD'],
      ['Processor', 'Intel Core i7-8650U (8th Gen)'],
      ['Memory', '16GB DDR4'],
      ['Storage', '512GB SSD'],
      ['OS', 'Windows 10 Pro'],
      ['Grade', 'A — minimal signs of use'],
    ],
    inBox: ['Laptop', 'Charger'],
    warranty: '6 months Steff Store warranty',
    art: 'laptop',
    badges: ['ex-uk'],
    added: '2026-03-05',
    rank: 79,
    keywords: 'dell latitude 7490 ex uk refurbished used i7',
  },
  {
    slug: 'lenovo-thinkpad-t480-ex-uk',
    name: 'Lenovo ThinkPad T480 (ex-UK)',
    brand: 'lenovo',
    category: 'laptops',
    price: 29999,
    condition: 'ex-uk',
    stock: 11,
    tagline: 'The tough ThinkPad with a hot-swap battery.',
    highlights: ['Intel Core i5 (8th Gen)', '8GB RAM · 256GB SSD', 'Dual batteries for long days'],
    description: 'Ex-UK ThinkPad T480 with two batteries — one swappable — so it keeps going through long days and power cuts. Graded A and tested.',
    specs: [
      ['Display', '14" FHD'],
      ['Processor', 'Intel Core i5-8350U (8th Gen)'],
      ['Memory', '8GB DDR4'],
      ['Storage', '256GB SSD'],
      ['Battery', 'Internal + external (hot-swappable)'],
      ['Grade', 'A — minimal signs of use'],
    ],
    inBox: ['Laptop', 'Charger'],
    warranty: '6 months Steff Store warranty',
    art: 'laptop',
    badges: ['ex-uk'],
    added: '2026-03-05',
    rank: 75,
    keywords: 'lenovo thinkpad t480 ex uk refurbished used',
  },
];

export const tablets: Product[] = [
  {
    slug: 'ipad-11-a16',
    name: 'iPad 11" (A16)',
    brand: 'apple',
    category: 'tablets',
    price: 57999,
    condition: 'new',
    stock: 6,
    tagline: 'The everyday iPad, now with double the storage.',
    highlights: ['11" Liquid Retina display', 'A16 chip', '128GB storage'],
    description: 'The 11-inch iPad with A16 handles notes, reading, streaming and light drawing, and works with Apple Pencil (USB‑C) and Magic Keyboard Folio.',
    specs: [
      ['Display', '11" Liquid Retina'],
      ['Chip', 'A16'],
      ['Storage', '128GB'],
      ['Connectivity', 'Wi‑Fi 6'],
      ['Cameras', '12MP back · 12MP landscape Center Stage front'],
      ['Connector', 'USB‑C'],
    ],
    inBox: ['iPad', 'USB‑C charge cable (1 m)'],
    warranty: '12 months Apple warranty',
    colours: [
      { name: 'Blue', hex: '#a9c3dc' },
      { name: 'Pink', hex: '#efc9d3' },
      { name: 'Yellow', hex: '#f1dc8a' },
      { name: 'Silver', hex: '#d8d9db' },
    ],
    art: 'tablet',
    added: '2026-03-20',
    rank: 83,
    keywords: 'apple ipad 11 a16 2025',
  },
  {
    slug: 'ipad-air-11-m3',
    name: 'iPad Air 11" M3',
    brand: 'apple',
    category: 'tablets',
    price: 91999,
    condition: 'new',
    stock: 3,
    tagline: 'M3 power for students, artists and note-takers.',
    highlights: ['11" Liquid Retina display', 'Apple M3 chip', 'Apple Pencil Pro support'],
    description: 'iPad Air with M3 is a laptop-class tablet for drawing, note-taking and editing, with Apple Pencil Pro and Magic Keyboard support.',
    specs: [
      ['Display', '11" Liquid Retina'],
      ['Chip', 'Apple M3'],
      ['Storage', '128GB'],
      ['Connectivity', 'Wi‑Fi 6E'],
      ['Connector', 'USB‑C'],
    ],
    inBox: ['iPad Air', 'USB‑C charge cable (1 m)'],
    warranty: '12 months Apple warranty',
    colours: [
      { name: 'Space Gray', hex: '#5b5d61' },
      { name: 'Blue', hex: '#a9bcd0' },
      { name: 'Purple', hex: '#c9bfe0' },
    ],
    art: 'tablet',
    added: '2026-03-20',
    rank: 72,
    keywords: 'apple ipad air m3',
  },
  {
    slug: 'samsung-galaxy-tab-a9-plus',
    name: 'Samsung Galaxy Tab A9+',
    brand: 'samsung',
    category: 'tablets',
    price: 27999,
    compareAt: 31999,
    condition: 'new',
    stock: 12,
    tagline: 'A big 11" screen and quad speakers for the family.',
    highlights: ['11" display, 90Hz', 'Quad speakers with Dolby Atmos', 'Kids mode built in'],
    description: 'Galaxy Tab A9+ is a family tablet with an 11-inch 90Hz screen, quad speakers and Samsung Kids for safe screen time.',
    specs: [
      ['Display', '11" WUXGA, 90Hz'],
      ['Processor', 'Snapdragon 695'],
      ['Memory', '4GB RAM'],
      ['Storage', '64GB · microSD supported'],
      ['Connectivity', 'Wi‑Fi'],
      ['Battery', '7,040mAh'],
    ],
    inBox: ['Galaxy Tab A9+', 'USB‑C cable', 'Ejection pin'],
    warranty: '12 months Samsung warranty',
    colours: [
      { name: 'Graphite', hex: '#3b3d40' },
      { name: 'Silver', hex: '#cfd1d4' },
    ],
    art: 'tablet',
    badges: ['deal'],
    added: '2026-02-05',
    rank: 81,
    keywords: 'samsung galaxy tab a9 plus kids tablet',
  },
  {
    slug: 'samsung-galaxy-tab-s10-fe',
    name: 'Samsung Galaxy Tab S10 FE',
    brand: 'samsung',
    category: 'tablets',
    price: 64999,
    condition: 'new',
    stock: 4,
    tagline: 'S Pen in the box and IP68 — study anywhere.',
    highlights: ['10.9" display, 90Hz', 'S Pen included', 'IP68 water and dust resistance'],
    description: 'Galaxy Tab S10 FE comes with an S Pen for notes and drawing, an IP68 rating and Galaxy AI tools for studying.',
    specs: [
      ['Display', '10.9" WUXGA+, 90Hz'],
      ['Processor', 'Exynos 1580'],
      ['Memory', '8GB RAM'],
      ['Storage', '128GB · microSD supported'],
      ['Water resistance', 'IP68'],
      ['Battery', '8,000mAh · 45W'],
    ],
    inBox: ['Galaxy Tab S10 FE', 'S Pen', 'USB‑C cable'],
    warranty: '12 months Samsung warranty',
    colours: [
      { name: 'Gray', hex: '#5b5d61' },
      { name: 'Blue', hex: '#9fb6cf' },
    ],
    art: 'tablet',
    added: '2026-02-05',
    rank: 63,
    keywords: 'samsung galaxy tab s10 fe s pen',
  },
  {
    slug: 'lenovo-tab-m11',
    name: 'Lenovo Tab M11',
    brand: 'lenovo',
    category: 'tablets',
    price: 25999,
    condition: 'new',
    stock: 9,
    tagline: 'Pen-ready study tablet at a fair price.',
    highlights: ['11" display, 90Hz', 'Lenovo Tab Pen support', 'Quad Dolby Atmos speakers'],
    description: 'Tab M11 is a capable study tablet with an 11-inch 90Hz display, quad speakers and support for Lenovo Tab Pen.',
    specs: [
      ['Display', '11" WUXGA, 90Hz'],
      ['Processor', 'MediaTek Helio G88'],
      ['Memory', '4GB RAM'],
      ['Storage', '128GB · microSD supported'],
      ['Battery', '7,040mAh'],
    ],
    inBox: ['Lenovo Tab M11', 'Charger', 'USB‑C cable'],
    warranty: '12 months Lenovo warranty',
    colours: [{ name: 'Luna Grey', hex: '#6a6d72' }],
    art: 'tablet',
    added: '2026-02-05',
    rank: 60,
    keywords: 'lenovo tab m11',
  },
];

export const monitors: Product[] = [
  {
    slug: 'dell-24-monitor-se2425h',
    name: 'Dell 24 Monitor SE2425H',
    brand: 'dell',
    category: 'monitors',
    price: 15499,
    condition: 'new',
    stock: 14,
    tagline: 'A clean, comfortable second screen for the office.',
    highlights: ['23.8" Full HD, 75Hz', 'ComfortView low blue light', 'HDMI and VGA'],
    description: 'A dependable 24-inch Full HD office monitor with thin bezels, flicker-free viewing and both HDMI and VGA inputs.',
    specs: [
      ['Panel', '23.8" VA, 1920 × 1080'],
      ['Refresh rate', '75Hz'],
      ['Inputs', 'HDMI 1.4 · VGA'],
      ['Eye care', 'ComfortView, flicker-free'],
      ['Mount', 'VESA 100 × 100'],
    ],
    inBox: ['Monitor', 'Stand', 'Power cable', 'HDMI cable'],
    warranty: '12 months Dell warranty',
    art: 'monitor',
    added: '2026-02-01',
    rank: 70,
    keywords: 'dell 24 monitor se2425h office screen',
  },
  {
    slug: 'samsung-odyssey-g5-27',
    name: 'Samsung Odyssey G5 27" QHD',
    brand: 'samsung',
    category: 'monitors',
    price: 37999,
    compareAt: 42999,
    condition: 'new',
    stock: 5,
    tagline: 'Curved QHD at 165Hz for gaming and creative work.',
    highlights: ['27" QHD 1000R curve', '165Hz · 1ms', 'AMD FreeSync Premium'],
    description: 'Odyssey G5 wraps a sharp 1440p panel around you with a 1000R curve and a fast 165Hz refresh rate.',
    specs: [
      ['Panel', '27" VA curved, 2560 × 1440'],
      ['Refresh rate', '165Hz · 1ms (MPRT)'],
      ['HDR', 'HDR10'],
      ['Inputs', 'HDMI · DisplayPort'],
      ['Sync', 'AMD FreeSync Premium'],
    ],
    inBox: ['Monitor', 'Stand', 'Power adapter', 'HDMI cable'],
    warranty: '12 months Samsung warranty',
    art: 'monitor',
    badges: ['deal'],
    added: '2026-02-01',
    rank: 66,
    keywords: 'samsung odyssey g5 27 gaming monitor curved',
  },
  {
    slug: 'lg-ultragear-24gn60r',
    name: 'LG UltraGear 24" 144Hz',
    brand: 'lg',
    category: 'monitors',
    price: 23999,
    condition: 'new',
    stock: 7,
    tagline: 'Fast IPS gaming without breaking the bank.',
    highlights: ['23.8" IPS Full HD', '144Hz · 1ms', 'HDR10 support'],
    description: 'UltraGear 24GN60R is a quick, colour-accurate IPS gaming monitor that suits esports and everyday work alike.',
    specs: [
      ['Panel', '23.8" IPS, 1920 × 1080'],
      ['Refresh rate', '144Hz · 1ms (GtG)'],
      ['Inputs', 'HDMI · DisplayPort'],
      ['Sync', 'AMD FreeSync Premium'],
    ],
    inBox: ['Monitor', 'Stand', 'Power adapter', 'HDMI cable'],
    warranty: '12 months LG warranty',
    art: 'monitor',
    added: '2026-02-01',
    rank: 62,
    keywords: 'lg ultragear 24gn60r gaming monitor',
  },
  {
    slug: 'imac-24-m4',
    name: 'iMac 24" M4',
    brand: 'apple',
    category: 'monitors',
    price: 219999,
    condition: 'new',
    stock: 2,
    tagline: 'An all-in-one for the reception desk, studio or home.',
    highlights: ['24" 4.5K Retina display', 'Apple M4 · 16GB memory', 'Keyboard and mouse included'],
    description: 'iMac with M4 is a beautiful all-in-one: a 4.5K Retina display, a 12MP Center Stage camera and colour-matched accessories.',
    specs: [
      ['Display', '24" 4.5K Retina'],
      ['Chip', 'Apple M4 · 8-core CPU · 8-core GPU'],
      ['Memory', '16GB unified memory'],
      ['Storage', '256GB SSD'],
      ['Camera', '12MP Center Stage'],
    ],
    inBox: ['iMac', 'Magic Keyboard', 'Magic Mouse', 'Power adapter', 'USB‑C cable'],
    warranty: '12 months Apple warranty',
    colours: [
      { name: 'Blue', hex: '#8fb3d6' },
      { name: 'Green', hex: '#a9c9a4' },
      { name: 'Silver', hex: '#d8d9db' },
    ],
    art: 'desktop',
    added: '2026-03-01',
    rank: 58,
    keywords: 'apple imac 24 m4 all in one',
  },
  {
    slug: 'hp-prodesk-400-g9-sff',
    name: 'HP ProDesk 400 G9 SFF',
    brand: 'hp',
    category: 'monitors',
    price: 74999,
    condition: 'new',
    stock: 6,
    tagline: 'A compact office desktop that just works.',
    highlights: ['12th Gen Intel Core i5', '8GB RAM · 512GB SSD', 'Small form factor'],
    description: 'ProDesk 400 G9 SFF is a compact, upgradeable office PC for front desks, schools and accounts teams.',
    specs: [
      ['Processor', 'Intel Core i5-12500 (12th Gen)'],
      ['Memory', '8GB DDR4'],
      ['Storage', '512GB NVMe SSD'],
      ['Ports', 'DisplayPort · HDMI · USB‑A · USB‑C · RJ45'],
      ['OS', 'FreeDOS (Windows 11 available)'],
    ],
    inBox: ['Desktop unit', 'Keyboard', 'Mouse', 'Power cable'],
    warranty: '12 months HP warranty',
    art: 'tower',
    added: '2026-03-01',
    rank: 55,
    keywords: 'hp prodesk 400 g9 desktop office pc',
  },
];
