import type { Product } from '../types';

export const tvs: Product[] = [
  {
    slug: 'lg-oled-evo-c4-65',
    name: 'LG 65" OLED evo C4',
    brand: 'lg',
    category: 'tvs',
    price: 324999,
    compareAt: 359999,
    condition: 'new',
    stock: 2,
    tagline: 'Perfect blacks and 144Hz — the cinema-and-gaming TV.',
    highlights: ['Self-lit OLED evo panel', 'α9 Gen7 AI Processor 4K', '144Hz with Dolby Vision gaming'],
    description:
      'LG’s C4 OLED evo delivers perfect blacks, infinite contrast and a 144Hz refresh rate. With Dolby Vision, Dolby Atmos and four HDMI 2.1 ports it is as good for football as it is for PS5.',
    specs: [
      ['Screen', '65" 4K OLED evo'],
      ['Processor', 'α9 Gen7 AI Processor 4K'],
      ['Refresh rate', 'Up to 144Hz · VRR · G-Sync compatible'],
      ['HDR', 'Dolby Vision · HDR10 · HLG'],
      ['Audio', 'Dolby Atmos'],
      ['Smart platform', 'webOS'],
      ['Ports', '4 × HDMI 2.1 · 3 × USB · Ethernet'],
    ],
    inBox: ['TV', 'Stand', 'Magic Remote', 'Power cable'],
    warranty: '12 months LG warranty',
    options: { label: 'Size', values: [{ name: '65"' }, { name: '55"', delta: -95000 }] },
    art: 'tv',
    badges: ['deal'],
    added: '2026-04-10',
    rank: 87,
    keywords: 'lg oled c4 65 inch tv',
  },
  {
    slug: 'samsung-65-qled-q60d',
    name: 'Samsung 65" QLED Q60D',
    brand: 'samsung',
    category: 'tvs',
    price: 109999,
    condition: 'new',
    stock: 4,
    tagline: 'Quantum Dot colour in a slim AirSlim design.',
    highlights: ['100% Colour Volume with Quantum Dot', 'Quantum Processor Lite 4K', 'Tizen smart TV with Samsung TV Plus'],
    description: 'The Q60D brings Quantum Dot colour and a slim AirSlim design to a big 65-inch screen, with Tizen apps and Samsung TV Plus built in.',
    specs: [
      ['Screen', '65" 4K QLED'],
      ['Processor', 'Quantum Processor Lite 4K'],
      ['HDR', 'Quantum HDR · HDR10+'],
      ['Smart platform', 'Tizen'],
      ['Ports', '3 × HDMI · 2 × USB'],
    ],
    inBox: ['TV', 'Feet stand', 'Remote', 'Power cable'],
    warranty: '12 months Samsung warranty',
    options: { label: 'Size', values: [{ name: '65"' }, { name: '55"', delta: -32000 }, { name: '75"', delta: 65000 }] },
    art: 'tv',
    added: '2026-03-25',
    rank: 80,
    keywords: 'samsung qled q60d 65 inch tv',
  },
  {
    slug: 'samsung-55-crystal-uhd-du7000',
    name: 'Samsung 55" Crystal UHD DU7000',
    brand: 'samsung',
    category: 'tvs',
    price: 56999,
    compareAt: 62999,
    condition: 'new',
    stock: 9,
    tagline: 'Sharp 4K from Samsung at a mid-range price.',
    highlights: ['55" 4K Crystal UHD', 'Crystal Processor 4K', 'HDR10+ and PurColor'],
    description: 'A dependable 55-inch 4K smart TV from Samsung with Crystal Processor 4K upscaling, HDR10+ and the full Tizen app store.',
    specs: [
      ['Screen', '55" 4K UHD'],
      ['Processor', 'Crystal Processor 4K'],
      ['HDR', 'HDR10+'],
      ['Smart platform', 'Tizen'],
      ['Ports', '3 × HDMI · 1 × USB'],
    ],
    inBox: ['TV', 'Feet stand', 'Remote', 'Power cable'],
    warranty: '12 months Samsung warranty',
    options: { label: 'Size', values: [{ name: '55"' }, { name: '43"', delta: -17000 }, { name: '65"', delta: 24000 }] },
    art: 'tv',
    badges: ['deal'],
    added: '2026-03-25',
    rank: 93,
    keywords: 'samsung 55 crystal uhd du7000 4k tv',
  },
  {
    slug: 'lg-43-uhd-ut80',
    name: 'LG 43" UHD UT80',
    brand: 'lg',
    category: 'tvs',
    price: 39999,
    condition: 'new',
    stock: 8,
    tagline: 'A 4K bedroom or office TV with webOS.',
    highlights: ['43" 4K UHD', 'α5 Gen7 AI Processor 4K', 'webOS with Magic Remote support'],
    description: 'LG UT80 is a compact 4K smart TV with AI upscaling, HDR10 and the easy webOS interface.',
    specs: [
      ['Screen', '43" 4K UHD'],
      ['Processor', 'α5 Gen7 AI Processor 4K'],
      ['HDR', 'HDR10 · HLG'],
      ['Smart platform', 'webOS'],
    ],
    inBox: ['TV', 'Stand', 'Remote', 'Power cable'],
    warranty: '12 months LG warranty',
    art: 'tv',
    added: '2026-03-25',
    rank: 66,
    keywords: 'lg 43 ut80 4k tv',
  },
  {
    slug: 'hisense-55-a6-4k',
    name: 'Hisense 55" A6 4K Smart TV',
    brand: 'hisense',
    category: 'tvs',
    price: 47999,
    condition: 'new',
    stock: 10,
    tagline: 'Big-screen 4K with Dolby Vision for less.',
    highlights: ['55" 4K UHD', 'Dolby Vision and HDR10', 'VIDAA smart TV with Netflix and YouTube'],
    description: 'Hisense A6 is a strong value 4K TV with Dolby Vision, DTS Virtual:X sound and the fast VIDAA smart platform.',
    specs: [
      ['Screen', '55" 4K UHD'],
      ['HDR', 'Dolby Vision · HDR10 · HLG'],
      ['Audio', 'DTS Virtual:X'],
      ['Smart platform', 'VIDAA'],
      ['Ports', '3 × HDMI · 2 × USB'],
    ],
    inBox: ['TV', 'Feet stand', 'Remote', 'Power cable'],
    warranty: '12 months Hisense warranty',
    options: { label: 'Size', values: [{ name: '55"' }, { name: '50"', delta: -6000 }, { name: '65"', delta: 21000 }] },
    art: 'tv',
    badges: ['pick'],
    added: '2026-03-10',
    rank: 88,
    keywords: 'hisense 55 a6 4k smart tv',
  },
  {
    slug: 'hisense-43-a4-fhd',
    name: 'Hisense 43" A4 Full HD Smart TV',
    brand: 'hisense',
    category: 'tvs',
    price: 26999,
    condition: 'new',
    stock: 14,
    tagline: 'A sensible smart TV for the living room or hostel.',
    highlights: ['43" Full HD', 'VIDAA smart TV', 'Dolby Audio'],
    description: 'Hisense A4 is a simple, reliable Full HD smart TV with the apps you need and clear Dolby Audio.',
    specs: [
      ['Screen', '43" Full HD'],
      ['Smart platform', 'VIDAA'],
      ['Audio', 'Dolby Audio'],
      ['Ports', '2 × HDMI · 1 × USB'],
    ],
    inBox: ['TV', 'Feet stand', 'Remote', 'Power cable'],
    warranty: '12 months Hisense warranty',
    art: 'tv',
    added: '2026-03-10',
    rank: 77,
    keywords: 'hisense 43 a4 smart tv',
  },
  {
    slug: 'tcl-55-c655-qled',
    name: 'TCL 55" C655 QLED Google TV',
    brand: 'tcl',
    category: 'tvs',
    price: 59999,
    compareAt: 66999,
    condition: 'new',
    stock: 6,
    tagline: 'QLED colour and Google TV — the best of both.',
    highlights: ['55" 4K QLED', 'Google TV with Google Assistant', 'Dolby Vision · Dolby Atmos'],
    description: 'TCL C655 combines Quantum Dot colour with Google TV, so every app is there and recommendations come from all your services.',
    specs: [
      ['Screen', '55" 4K QLED'],
      ['HDR', 'Dolby Vision · HDR10+ · HLG'],
      ['Audio', 'Dolby Atmos'],
      ['Smart platform', 'Google TV'],
      ['Gaming', 'Game Master, ALLM'],
    ],
    inBox: ['TV', 'Feet stand', 'Voice remote', 'Power cable'],
    warranty: '12 months TCL warranty',
    art: 'tv',
    badges: ['deal'],
    added: '2026-03-10',
    rank: 84,
    keywords: 'tcl 55 c655 qled google tv',
  },
  {
    slug: 'sony-bravia-55-x77l',
    name: 'Sony Bravia 55" X77L 4K Google TV',
    brand: 'sony',
    category: 'tvs',
    price: 84999,
    condition: 'new',
    stock: 3,
    tagline: 'Natural Sony picture processing with Google TV.',
    highlights: ['55" 4K HDR', '4K HDR Processor X1', 'Google TV with Chromecast built-in'],
    description: 'Sony X77L brings Sony’s natural colour and motion processing, Google TV and Chromecast built in.',
    specs: [
      ['Screen', '55" 4K LED'],
      ['Processor', '4K HDR Processor X1'],
      ['HDR', 'HDR10 · HLG'],
      ['Smart platform', 'Google TV'],
    ],
    inBox: ['TV', 'Feet stand', 'Voice remote', 'Power cable'],
    warranty: '12 months Sony warranty',
    art: 'tv',
    added: '2026-02-20',
    rank: 68,
    keywords: 'sony bravia 55 x77l google tv',
  },
  {
    slug: 'vitron-32-smart-android-tv',
    name: 'Vitron 32" Frameless Smart Android TV',
    brand: 'vitron',
    category: 'tvs',
    price: 13499,
    condition: 'new',
    stock: 24,
    tagline: 'An affordable smart TV with YouTube and Netflix built in.',
    highlights: ['32" HD frameless screen', 'Android smart TV', 'Built-in free-to-air decoder'],
    description: 'An everyday 32-inch smart TV with a built-in digital decoder, Android apps and a frameless design — great for bedrooms, shops and hostels.',
    specs: [
      ['Screen', '32" HD'],
      ['Smart platform', 'Android TV'],
      ['Tuner', 'Built-in digital free-to-air'],
      ['Ports', '2 × HDMI · 2 × USB'],
    ],
    inBox: ['TV', 'Feet stand', 'Remote', 'Power cable'],
    warranty: '12 months Vitron warranty',
    options: { label: 'Size', values: [{ name: '32"' }, { name: '43"', delta: 7500 }] },
    art: 'tv',
    added: '2026-02-20',
    rank: 79,
    keywords: 'vitron 32 smart android tv cheap',
  },
];

export const audio: Product[] = [
  {
    slug: 'sony-wh-1000xm5',
    name: 'Sony WH-1000XM5',
    brand: 'sony',
    category: 'audio',
    price: 46999,
    compareAt: 52999,
    condition: 'new',
    stock: 5,
    tagline: 'Industry-leading noise cancelling for matatus, flights and focus.',
    highlights: ['Industry-leading noise cancelling', 'Up to 30 hours battery', 'Crystal-clear calls with 8 mics'],
    description: 'Sony’s WH-1000XM5 blocks out the world with eight microphones and two processors, and lasts up to 30 hours on a charge.',
    specs: [
      ['Type', 'Over-ear, wireless'],
      ['Noise cancelling', 'Yes — Auto NC Optimizer'],
      ['Battery', 'Up to 30 hours (NC on)'],
      ['Charging', 'USB‑C · 3 min = 3 hours'],
      ['Codecs', 'SBC · AAC · LDAC'],
    ],
    inBox: ['Headphones', 'Carry case', 'USB‑C cable', 'Audio cable'],
    warranty: '12 months Sony warranty',
    colours: [
      { name: 'Black', hex: '#232427' },
      { name: 'Silver', hex: '#d9d6cf' },
    ],
    art: 'headphones',
    badges: ['deal'],
    added: '2026-02-14',
    rank: 86,
    keywords: 'sony wh1000xm5 xm5 noise cancelling headphones',
  },
  {
    slug: 'airpods-4-anc',
    name: 'AirPods 4 with Active Noise Cancellation',
    brand: 'apple',
    category: 'audio',
    price: 29999,
    condition: 'new',
    stock: 8,
    tagline: 'Open-fit comfort with noise cancelling for iPhone users.',
    highlights: ['Active Noise Cancellation', 'Personalised Spatial Audio', 'USB‑C and wireless charging case'],
    description: 'AirPods 4 with ANC combine an open-fit design with active noise cancellation, Transparency mode and a case with a speaker for Find My.',
    specs: [
      ['Type', 'Earbuds, open fit'],
      ['Chip', 'H2'],
      ['Noise cancelling', 'Active Noise Cancellation · Transparency'],
      ['Case', 'USB‑C · wireless charging · speaker'],
      ['Water resistance', 'IP54'],
    ],
    inBox: ['AirPods 4', 'Charging case'],
    warranty: '12 months Apple warranty',
    art: 'earbuds',
    added: '2026-03-01',
    rank: 75,
    keywords: 'apple airpods 4 anc earbuds',
  },
  {
    slug: 'samsung-galaxy-buds3-pro',
    name: 'Samsung Galaxy Buds3 Pro',
    brand: 'samsung',
    category: 'audio',
    price: 27999,
    condition: 'new',
    stock: 6,
    tagline: 'Hi-fi sound and adaptive ANC for Galaxy phones.',
    highlights: ['Adaptive noise control', '24-bit Hi-Fi audio', 'Galaxy AI interpreter mode'],
    description: 'Galaxy Buds3 Pro pair hi-fi audio with adaptive noise control and work beautifully with Galaxy AI features on Samsung phones.',
    specs: [
      ['Type', 'In-ear, wireless'],
      ['Noise cancelling', 'Adaptive ANC'],
      ['Battery', 'Up to 6h buds (ANC on) · 26h with case'],
      ['Water resistance', 'IP57'],
    ],
    inBox: ['Buds', 'Charging case', 'Ear tips (S/M/L)', 'USB‑C cable'],
    warranty: '12 months Samsung warranty',
    colours: [
      { name: 'Silver', hex: '#d0d2d4' },
      { name: 'White', hex: '#f1f1ee' },
    ],
    art: 'earbuds',
    added: '2026-03-01',
    rank: 62,
    keywords: 'samsung galaxy buds3 pro earbuds',
  },
  {
    slug: 'oraimo-freepods-4',
    name: 'Oraimo FreePods 4',
    brand: 'oraimo',
    category: 'audio',
    price: 3499,
    compareAt: 3999,
    condition: 'new',
    stock: 40,
    tagline: 'Noise-cancelling earbuds for the price of lunch for two.',
    highlights: ['Active noise cancellation', 'Up to 35.5 hours with case', 'Fast charge'],
    description: 'FreePods 4 bring active noise cancellation, punchy bass and long battery life to a very friendly price.',
    specs: [
      ['Type', 'In-ear, wireless'],
      ['Noise cancelling', 'ANC'],
      ['Battery', 'Up to 35.5 hours with case'],
      ['Charging', 'USB‑C'],
    ],
    inBox: ['Earbuds', 'Charging case', 'Ear tips', 'USB‑C cable'],
    warranty: '12 months Oraimo warranty',
    colours: [
      { name: 'Black', hex: '#232427' },
      { name: 'White', hex: '#f1f1ee' },
    ],
    art: 'earbuds',
    badges: ['deal'],
    added: '2026-01-12',
    rank: 90,
    keywords: 'oraimo freepods 4 earbuds cheap',
  },
  {
    slug: 'jbl-flip-6',
    name: 'JBL Flip 6',
    brand: 'jbl',
    category: 'audio',
    price: 14999,
    condition: 'new',
    stock: 12,
    tagline: 'Bold JBL sound that survives the beach and the bathroom.',
    highlights: ['IP67 waterproof and dustproof', 'Up to 12 hours playtime', 'PartyBoost pairing'],
    description: 'JBL Flip 6 is the portable speaker people recommend: big, clear sound from a two-way driver, IP67 protection and 12 hours of play.',
    specs: [
      ['Output', '20W woofer + 10W tweeter'],
      ['Battery', 'Up to 12 hours'],
      ['Water resistance', 'IP67'],
      ['Connectivity', 'Bluetooth 5.1 · PartyBoost'],
    ],
    inBox: ['Speaker', 'USB‑C cable'],
    warranty: '12 months JBL warranty',
    colours: [
      { name: 'Black', hex: '#232427' },
      { name: 'Blue', hex: '#2f5f9e' },
      { name: 'Red', hex: '#b8322a' },
    ],
    art: 'speaker',
    badges: ['pick'],
    added: '2026-01-12',
    rank: 87,
    keywords: 'jbl flip 6 bluetooth speaker',
  },
  {
    slug: 'jbl-charge-5',
    name: 'JBL Charge 5',
    brand: 'jbl',
    category: 'audio',
    price: 21999,
    condition: 'new',
    stock: 7,
    tagline: 'A bigger sound and a power bank built in.',
    highlights: ['Up to 20 hours playtime', 'Built-in power bank', 'IP67 waterproof'],
    description: 'Charge 5 adds deeper bass, 20 hours of playtime and a built-in power bank to charge your phone at the shamba or the beach.',
    specs: [
      ['Output', '30W woofer + 10W tweeter'],
      ['Battery', 'Up to 20 hours · charges your phone'],
      ['Water resistance', 'IP67'],
      ['Connectivity', 'Bluetooth 5.1 · PartyBoost'],
    ],
    inBox: ['Speaker', 'USB‑C cable'],
    warranty: '12 months JBL warranty',
    colours: [
      { name: 'Black', hex: '#232427' },
      { name: 'Camo', hex: '#5b6448' },
    ],
    art: 'speaker',
    added: '2026-01-12',
    rank: 73,
    keywords: 'jbl charge 5 speaker',
  },
  {
    slug: 'jbl-partybox-110',
    name: 'JBL PartyBox 110',
    brand: 'jbl',
    category: 'audio',
    price: 52999,
    condition: 'new',
    stock: 3,
    tagline: '160W of party sound with a light show.',
    highlights: ['160W output with deep bass', 'Light show synced to the music', 'Mic and guitar inputs'],
    description: 'PartyBox 110 fills the compound with 160W of JBL Original Pro Sound, a synced light show and inputs for a mic or guitar.',
    specs: [
      ['Output', '160W RMS'],
      ['Battery', 'Up to 12 hours'],
      ['Water resistance', 'IPX4 splash-proof'],
      ['Inputs', 'Mic · guitar · AUX · USB'],
    ],
    inBox: ['Speaker', 'Power cable'],
    warranty: '12 months JBL warranty',
    art: 'partybox',
    added: '2026-01-12',
    rank: 64,
    keywords: 'jbl partybox 110 party speaker',
  },
  {
    slug: 'samsung-hw-c450-soundbar',
    name: 'Samsung HW-C450 2.1 Soundbar',
    brand: 'samsung',
    category: 'audio',
    price: 24999,
    compareAt: 28999,
    condition: 'new',
    stock: 6,
    tagline: 'Proper TV sound with a wireless subwoofer.',
    highlights: ['300W 2.1 channel', 'Wireless subwoofer', 'Bass boost and game mode'],
    description: 'HW-C450 lifts dialogue and adds real bass to any TV with a wireless subwoofer and DTS Virtual:X.',
    specs: [
      ['Channels', '2.1'],
      ['Output', '300W'],
      ['Subwoofer', 'Wireless'],
      ['Connectivity', 'Bluetooth · optical · USB'],
    ],
    inBox: ['Soundbar', 'Subwoofer', 'Remote', 'Optical cable', 'Wall-mount kit'],
    warranty: '12 months Samsung warranty',
    art: 'soundbar',
    badges: ['deal'],
    added: '2026-03-25',
    rank: 72,
    keywords: 'samsung hw c450 soundbar',
  },
  {
    slug: 'sony-ht-s100f-soundbar',
    name: 'Sony HT-S100F Soundbar',
    brand: 'sony',
    category: 'audio',
    price: 17999,
    condition: 'new',
    stock: 5,
    tagline: 'A compact soundbar that makes speech clear.',
    highlights: ['2-channel with built-in tweeter', 'S-Force Pro Front Surround', 'HDMI ARC and Bluetooth'],
    description: 'A slim, simple upgrade over TV speakers: clearer voices, wider sound and one-cable HDMI ARC set-up.',
    specs: [
      ['Channels', '2.0'],
      ['Connectivity', 'HDMI ARC · Bluetooth · optical · USB'],
      ['Mount', 'Wall-mountable'],
    ],
    inBox: ['Soundbar', 'Remote', 'Wall-mount template'],
    warranty: '12 months Sony warranty',
    art: 'soundbar',
    added: '2026-03-25',
    rank: 58,
    keywords: 'sony ht s100f soundbar',
  },
];

export const gaming: Product[] = [
  {
    slug: 'playstation-5-slim-disc',
    name: 'PlayStation 5 Slim (Disc)',
    brand: 'playstation',
    category: 'gaming',
    price: 84999,
    compareAt: 92999,
    condition: 'new',
    stock: 5,
    tagline: 'The console Kenya plays FC on — now slimmer, with 1TB.',
    highlights: ['1TB SSD storage', 'Ultra HD Blu-ray drive', 'DualSense wireless controller'],
    description: 'PS5 Slim keeps the speed of the original in a smaller body with more storage. Includes the disc drive and a DualSense controller.',
    specs: [
      ['Storage', '1TB SSD'],
      ['Drive', 'Ultra HD Blu-ray'],
      ['Output', 'Up to 4K 120Hz · HDR'],
      ['Controller', 'DualSense wireless'],
    ],
    inBox: ['PS5 Slim console', 'DualSense controller', 'HDMI cable', 'Power cable', 'USB cable'],
    warranty: '12 months Steff Store warranty',
    options: { label: 'Edition', values: [{ name: 'Disc' }, { name: 'Digital', delta: -12000 }] },
    art: 'console',
    badges: ['deal', 'pick'],
    added: '2026-02-01',
    rank: 99,
    keywords: 'sony playstation 5 ps5 slim console',
  },
  {
    slug: 'dualsense-wireless-controller',
    name: 'DualSense Wireless Controller',
    brand: 'playstation',
    category: 'gaming',
    price: 10999,
    condition: 'new',
    stock: 14,
    tagline: 'A second controller for two-player FC nights.',
    highlights: ['Haptic feedback', 'Adaptive triggers', 'Built-in microphone'],
    description: 'The official PS5 controller with haptic feedback and adaptive triggers. Every two-player household needs a second one.',
    specs: [
      ['Compatibility', 'PS5 · PC'],
      ['Connectivity', 'Bluetooth · USB‑C'],
      ['Features', 'Haptics · adaptive triggers · mic · speaker'],
    ],
    inBox: ['Controller'],
    warranty: '12 months Steff Store warranty',
    colours: [
      { name: 'White', hex: '#f1f1ee' },
      { name: 'Midnight Black', hex: '#232427' },
      { name: 'Cosmic Red', hex: '#a8262f' },
    ],
    art: 'controller',
    added: '2026-02-01',
    rank: 80,
    keywords: 'ps5 dualsense controller pad',
  },
  {
    slug: 'ea-sports-fc-26-ps5',
    name: 'EA SPORTS FC 26 (PS5)',
    brand: 'ea',
    category: 'gaming',
    price: 8999,
    condition: 'new',
    stock: 20,
    tagline: 'This season’s football game, on disc.',
    highlights: ['Physical PS5 disc', 'Career, Ultimate Team and Clubs', 'Play with friends locally'],
    description: 'The latest EA SPORTS FC on a physical PS5 disc — easy to share and resell.',
    specs: [
      ['Platform', 'PlayStation 5'],
      ['Format', 'Physical disc'],
      ['Players', '1–4 local · online'],
    ],
    inBox: ['Game disc in case'],
    warranty: 'Replacement if disc is faulty',
    art: 'gamecase',
    badges: ['new'],
    added: '2026-09-26',
    rank: 85,
    keywords: 'fifa fc 26 ea sports ps5 game',
  },
  {
    slug: 'xbox-series-x',
    name: 'Xbox Series X 1TB',
    brand: 'microsoft',
    category: 'gaming',
    price: 89999,
    condition: 'new',
    stock: 2,
    tagline: 'The most powerful Xbox, built for Game Pass.',
    highlights: ['True 4K gaming up to 120fps', '1TB custom SSD', 'Xbox Game Pass ready'],
    description: 'Xbox Series X delivers true 4K gaming, fast loading with Quick Resume and access to hundreds of games through Game Pass.',
    specs: [
      ['Storage', '1TB SSD'],
      ['Drive', '4K UHD Blu-ray'],
      ['Output', 'Up to 4K 120fps'],
    ],
    inBox: ['Console', 'Wireless controller', 'HDMI cable', 'Power cable'],
    warranty: '12 months Steff Store warranty',
    art: 'xbox',
    added: '2026-02-01',
    rank: 66,
    keywords: 'microsoft xbox series x console',
  },
  {
    slug: 'nintendo-switch-2',
    name: 'Nintendo Switch 2',
    brand: 'nintendo',
    category: 'gaming',
    price: 74999,
    condition: 'new',
    stock: 3,
    tagline: 'A bigger screen, magnetic Joy-Con 2 and 256GB.',
    highlights: ['7.9" 1080p display, up to 120Hz', '256GB storage', 'Play on TV or on the go'],
    description: 'Switch 2 brings a larger, sharper screen, magnetic Joy-Con 2 controllers and 4K output when docked.',
    specs: [
      ['Screen', '7.9" LCD, 1080p, HDR, up to 120Hz'],
      ['Storage', '256GB · microSD Express'],
      ['TV output', 'Up to 4K'],
    ],
    inBox: ['Console', 'Joy-Con 2 (L/R)', 'Joy-Con 2 grip', 'Dock', 'AC adapter', 'HDMI cable'],
    warranty: '12 months Steff Store warranty',
    art: 'handheld',
    badges: ['new'],
    added: '2026-06-15',
    rank: 82,
    keywords: 'nintendo switch 2 console',
  },
];
