import type { Product } from '../types';

export const wearables: Product[] = [
  {
    slug: 'apple-watch-series-10',
    name: 'Apple Watch Series 10',
    brand: 'apple',
    category: 'wearables',
    price: 57999,
    condition: 'new',
    stock: 4,
    tagline: 'The thinnest Apple Watch, with the biggest display yet.',
    highlights: ['Wide-angle OLED display', 'Sleep apnoea notifications', 'Fast charging — 80% in about 30 min'],
    description: 'Apple Watch Series 10 has the biggest, brightest display yet in the thinnest case, with advanced health and fitness tracking.',
    specs: [
      ['Case', '42mm aluminium'],
      ['Display', 'Always-On wide-angle OLED'],
      ['Health', 'ECG · blood oxygen · sleep apnoea notifications'],
      ['Connectivity', 'GPS'],
      ['Water resistance', '50m'],
    ],
    inBox: ['Watch', 'Sport band', 'Magnetic fast charger (USB‑C)'],
    warranty: '12 months Apple warranty',
    colours: [
      { name: 'Jet Black', hex: '#1d1d1f' },
      { name: 'Rose Gold', hex: '#e7c8bd' },
      { name: 'Silver', hex: '#d8d9db' },
    ],
    options: { label: 'Case size', values: [{ name: '42mm' }, { name: '46mm', delta: 5000 }] },
    art: 'watch',
    added: '2026-03-01',
    rank: 76,
    keywords: 'apple watch series 10 smartwatch',
  },
  {
    slug: 'apple-watch-se-2',
    name: 'Apple Watch SE (2nd gen)',
    brand: 'apple',
    category: 'wearables',
    price: 35999,
    condition: 'new',
    stock: 6,
    tagline: 'The essentials of Apple Watch at the lowest price.',
    highlights: ['Crash and fall detection', 'Heart-rate notifications', 'Works with your iPhone'],
    description: 'Apple Watch SE covers activity, heart-rate alerts, crash detection and notifications — the essentials, well done.',
    specs: [
      ['Case', '40mm aluminium'],
      ['Connectivity', 'GPS'],
      ['Water resistance', '50m'],
    ],
    inBox: ['Watch', 'Sport band', 'Magnetic charger'],
    warranty: '12 months Apple warranty',
    colours: [
      { name: 'Midnight', hex: '#2e3641' },
      { name: 'Starlight', hex: '#e3dccf' },
    ],
    art: 'watch',
    added: '2026-03-01',
    rank: 61,
    keywords: 'apple watch se 2nd gen',
  },
  {
    slug: 'samsung-galaxy-watch7',
    name: 'Samsung Galaxy Watch7',
    brand: 'samsung',
    category: 'wearables',
    price: 33999,
    compareAt: 38999,
    condition: 'new',
    stock: 5,
    tagline: 'Health coaching and Galaxy AI on your wrist.',
    highlights: ['Energy Score and sleep coaching', 'Dual-frequency GPS', 'Wear OS with Google apps'],
    description: 'Galaxy Watch7 tracks sleep, workouts and heart health with Samsung’s BioActive sensor, and runs Wear OS apps.',
    specs: [
      ['Case', '40mm aluminium'],
      ['Display', 'Super AMOLED, sapphire crystal'],
      ['Health', 'BioActive sensor · ECG · body composition'],
      ['Water resistance', '5ATM · IP68'],
    ],
    inBox: ['Watch', 'Sport band', 'Wireless charger'],
    warranty: '12 months Samsung warranty',
    colours: [
      { name: 'Green', hex: '#5c6e55' },
      { name: 'Cream', hex: '#ece5d6' },
    ],
    art: 'watch',
    badges: ['deal'],
    added: '2026-03-01',
    rank: 67,
    keywords: 'samsung galaxy watch7 smartwatch',
  },
  {
    slug: 'samsung-galaxy-fit3',
    name: 'Samsung Galaxy Fit3',
    brand: 'samsung',
    category: 'wearables',
    price: 7499,
    condition: 'new',
    stock: 18,
    tagline: 'A big-screen fitness band with up to 13 days battery.',
    highlights: ['1.6" AMOLED display', 'Up to 13 days battery', '100+ workout modes'],
    description: 'Galaxy Fit3 tracks steps, sleep and workouts with a large AMOLED screen and nearly two weeks of battery.',
    specs: [
      ['Display', '1.6" AMOLED'],
      ['Battery', 'Up to 13 days'],
      ['Water resistance', '5ATM · IP68'],
    ],
    inBox: ['Band', 'Charging cable'],
    warranty: '12 months Samsung warranty',
    colours: [
      { name: 'Gray', hex: '#5b5d61' },
      { name: 'Pink Gold', hex: '#e7c8bd' },
    ],
    art: 'band',
    added: '2026-01-20',
    rank: 69,
    keywords: 'samsung galaxy fit3 fitness band',
  },
  {
    slug: 'redmi-watch-5-active',
    name: 'Redmi Watch 5 Active',
    brand: 'xiaomi',
    category: 'wearables',
    price: 5499,
    condition: 'new',
    stock: 22,
    tagline: 'Bluetooth calling and 18-day battery on a budget.',
    highlights: ['2" LCD display', 'Bluetooth calling', 'Up to 18 days battery'],
    description: 'Redmi Watch 5 Active lets you take calls from your wrist, track 140+ workouts and go up to 18 days between charges.',
    specs: [
      ['Display', '2" LCD'],
      ['Calling', 'Bluetooth calls'],
      ['Battery', 'Up to 18 days'],
      ['Water resistance', '5ATM'],
    ],
    inBox: ['Watch', 'Charging cable'],
    warranty: '12 months Xiaomi warranty',
    colours: [
      { name: 'Midnight Black', hex: '#25262a' },
      { name: 'Matte Silver', hex: '#c9cbce' },
    ],
    art: 'watch',
    added: '2026-01-20',
    rank: 71,
    keywords: 'xiaomi redmi watch 5 active smartwatch cheap',
  },
];

export const cameras: Product[] = [
  {
    slug: 'canon-eos-r50-kit',
    name: 'Canon EOS R50 + RF-S 18-45mm',
    brand: 'canon',
    category: 'cameras',
    price: 119999,
    condition: 'new',
    stock: 2,
    tagline: 'The easiest way into proper mirrorless photos and 4K video.',
    highlights: ['24.2MP APS-C sensor', '4K 30p uncropped video', 'Dual Pixel CMOS AF II subject tracking'],
    description: 'EOS R50 is a light, simple mirrorless camera for creators, churches and small studios, with excellent autofocus and 4K video.',
    specs: [
      ['Sensor', '24.2MP APS-C CMOS'],
      ['Video', '4K 30p (oversampled from 6K)'],
      ['Autofocus', 'Dual Pixel CMOS AF II'],
      ['Screen', '3" vari-angle touchscreen'],
      ['Lens', 'RF-S 18-45mm f/4.5-6.3 IS STM'],
    ],
    inBox: ['Camera body', '18-45mm lens', 'Battery', 'Charger', 'Strap'],
    warranty: '12 months Canon warranty',
    art: 'camera',
    added: '2026-03-01',
    rank: 70,
    keywords: 'canon eos r50 mirrorless camera kit',
  },
  {
    slug: 'gopro-hero13-black',
    name: 'GoPro HERO13 Black',
    brand: 'gopro',
    category: 'cameras',
    price: 64999,
    compareAt: 71999,
    condition: 'new',
    stock: 3,
    tagline: 'Rugged 5.3K action video, from boda rides to Hell’s Gate.',
    highlights: ['5.3K60 video', 'HyperSmooth 6.0 stabilisation', 'Waterproof to 10m'],
    description: 'HERO13 Black records stabilised 5.3K video, survives rain and dust, and is waterproof to 10 metres without a housing.',
    specs: [
      ['Video', '5.3K60 · 4K120'],
      ['Photo', '27MP'],
      ['Stabilisation', 'HyperSmooth 6.0'],
      ['Waterproof', '10m'],
    ],
    inBox: ['Camera', 'Enduro battery', 'Curved adhesive mount', 'Mounting buckle', 'USB‑C cable'],
    warranty: '12 months GoPro warranty',
    art: 'actioncam',
    badges: ['deal'],
    added: '2026-03-01',
    rank: 68,
    keywords: 'gopro hero13 hero 13 black action camera',
  },
  {
    slug: 'dji-osmo-pocket-3',
    name: 'DJI Osmo Pocket 3',
    brand: 'dji',
    category: 'cameras',
    price: 79999,
    condition: 'new',
    stock: 3,
    tagline: 'The creator’s pocket camera with a 1-inch sensor.',
    highlights: ['1-inch CMOS sensor', '3-axis mechanical stabilisation', '2" rotating touchscreen'],
    description: 'Osmo Pocket 3 is a pocket gimbal camera with a large 1-inch sensor for clean low-light video — ideal for vlogs, TikTok and events.',
    specs: [
      ['Sensor', '1-inch CMOS'],
      ['Video', '4K/120fps'],
      ['Stabilisation', '3-axis gimbal'],
      ['Screen', '2" rotatable touchscreen'],
    ],
    inBox: ['Osmo Pocket 3', 'Protective cover', 'Wrist strap', 'Handle with ¼" thread', 'USB‑C cable'],
    warranty: '12 months DJI warranty',
    art: 'gimbal',
    badges: ['pick'],
    added: '2026-03-01',
    rank: 74,
    keywords: 'dji osmo pocket 3 vlog camera',
  },
];

export const printers: Product[] = [
  {
    slug: 'epson-ecotank-l3250',
    name: 'Epson EcoTank L3250',
    brand: 'epson',
    category: 'printers',
    price: 28999,
    condition: 'new',
    stock: 8,
    tagline: 'Print, scan and copy for cents per page.',
    highlights: ['Refillable ink tanks', 'Wi‑Fi and Wi‑Fi Direct', 'Print, scan, copy'],
    description: 'EcoTank L3250 replaces cartridges with refillable tanks, so cyber cafés, schools and home offices pay far less per page.',
    specs: [
      ['Functions', 'Print · scan · copy'],
      ['Connectivity', 'Wi‑Fi · Wi‑Fi Direct · USB'],
      ['Ink', 'Refillable tanks (CMYK)'],
      ['Paper', 'Up to A4'],
    ],
    inBox: ['Printer', 'Ink bottles (black + colour)', 'Power cable', 'USB cable'],
    warranty: '12 months Epson warranty',
    art: 'printer',
    badges: ['pick'],
    added: '2026-02-01',
    rank: 78,
    keywords: 'epson ecotank l3250 ink tank printer',
  },
  {
    slug: 'hp-smart-tank-580',
    name: 'HP Smart Tank 580',
    brand: 'hp',
    category: 'printers',
    price: 26999,
    condition: 'new',
    stock: 6,
    tagline: 'High-volume ink-tank printing with the HP Smart app.',
    highlights: ['Up to 6,000 black pages per ink set', 'Wi‑Fi and Bluetooth', 'Print, scan, copy'],
    description: 'Smart Tank 580 prints thousands of pages from the included ink and sets up from your phone with HP Smart.',
    specs: [
      ['Functions', 'Print · scan · copy'],
      ['Connectivity', 'Wi‑Fi · Bluetooth · USB'],
      ['Ink', 'Refillable tanks'],
    ],
    inBox: ['Printer', 'Ink bottles', 'Printheads', 'Power cable'],
    warranty: '12 months HP warranty',
    art: 'printer',
    added: '2026-02-01',
    rank: 64,
    keywords: 'hp smart tank 580 printer',
  },
  {
    slug: 'hp-laserjet-m211dw',
    name: 'HP LaserJet M211dw',
    brand: 'hp',
    category: 'printers',
    price: 24999,
    compareAt: 27999,
    condition: 'new',
    stock: 5,
    tagline: 'Fast black-and-white printing with automatic two-sided.',
    highlights: ['Up to 29 pages per minute', 'Automatic duplex', 'Wi‑Fi and Ethernet'],
    description: 'LaserJet M211dw is a quick mono laser for offices that print invoices, reports and exams — on both sides automatically.',
    specs: [
      ['Functions', 'Print'],
      ['Speed', 'Up to 29 ppm (A4)'],
      ['Duplex', 'Automatic'],
      ['Connectivity', 'Wi‑Fi · Ethernet · USB'],
    ],
    inBox: ['Printer', 'Starter toner', 'Power cable'],
    warranty: '12 months HP warranty',
    art: 'printer',
    badges: ['deal'],
    added: '2026-02-01',
    rank: 60,
    keywords: 'hp laserjet m211dw laser printer',
  },
  {
    slug: 'apc-back-ups-650va',
    name: 'APC Back-UPS 650VA',
    brand: 'apc',
    category: 'printers',
    price: 9499,
    condition: 'new',
    stock: 15,
    tagline: 'Keep the desktop and router on when KPLC blinks.',
    highlights: ['650VA / 390W', 'Automatic voltage regulation', 'Surge protection'],
    description: 'A reliable UPS that keeps a desktop and router running through short power cuts and protects them from surges.',
    specs: [
      ['Capacity', '650VA / 390W'],
      ['Outlets', '4'],
      ['Protection', 'AVR · surge'],
    ],
    inBox: ['UPS', 'Power cable'],
    warranty: '24 months APC warranty',
    art: 'ups',
    added: '2026-02-01',
    rank: 72,
    keywords: 'apc ups back ups 650va power backup',
  },
];

export const networking: Product[] = [
  {
    slug: 'tp-link-deco-x20-2-pack',
    name: 'TP-Link Deco X20 Mesh Wi‑Fi 6 (2-pack)',
    brand: 'tp-link',
    category: 'networking',
    price: 21999,
    condition: 'new',
    stock: 6,
    tagline: 'Strong Wi‑Fi in every room — even through stone walls.',
    highlights: ['Wi‑Fi 6 AX1800', 'Covers up to 4,000 sq ft', 'Set up in minutes with the Deco app'],
    description: 'Deco X20 replaces one weak router with a mesh of two units, so Wi‑Fi reaches bedrooms, offices and the back of the shop.',
    specs: [
      ['Standard', 'Wi‑Fi 6 · AX1800'],
      ['Coverage', 'Up to 4,000 sq ft (2 units)'],
      ['Ports', '2 × Gigabit per unit'],
    ],
    inBox: ['2 × Deco X20 units', 'Ethernet cable', '2 × power adapters'],
    warranty: '24 months TP-Link warranty',
    art: 'mesh',
    badges: ['pick'],
    added: '2026-02-01',
    rank: 72,
    keywords: 'tp link deco x20 mesh wifi 6',
  },
  {
    slug: 'tp-link-archer-c6',
    name: 'TP-Link Archer C6 AC1200',
    brand: 'tp-link',
    category: 'networking',
    price: 5499,
    condition: 'new',
    stock: 18,
    tagline: 'A dual-band router upgrade for the home.',
    highlights: ['AC1200 dual-band Wi‑Fi', 'MU-MIMO', 'Gigabit ports'],
    description: 'Archer C6 is a solid, affordable dual-band router for fibre connections from Safaricom, Zuku and Faiba.',
    specs: [
      ['Standard', 'Wi‑Fi 5 · AC1200'],
      ['Ports', '4 × Gigabit LAN · 1 × Gigabit WAN'],
    ],
    inBox: ['Router', 'Power adapter', 'Ethernet cable'],
    warranty: '24 months TP-Link warranty',
    art: 'router',
    added: '2026-02-01',
    rank: 63,
    keywords: 'tp link archer c6 router',
  },
  {
    slug: 'tp-link-tl-mr6400-4g',
    name: 'TP-Link TL-MR6400 4G LTE Router',
    brand: 'tp-link',
    category: 'networking',
    price: 9499,
    condition: 'new',
    stock: 9,
    tagline: 'Pop in a SIM card and share 4G with the whole office.',
    highlights: ['Works with any Kenyan SIM', '300Mbps Wi‑Fi', 'No set-up needed'],
    description: 'TL-MR6400 turns a Safaricom, Airtel or Telkom data SIM into Wi‑Fi for up to 32 devices — great where fibre has not arrived.',
    specs: [
      ['Network', '4G LTE Cat4'],
      ['Wi‑Fi', '300Mbps 2.4GHz'],
      ['Ports', 'LAN/WAN Ethernet'],
    ],
    inBox: ['Router', '2 × antennas', 'Power adapter', 'Ethernet cable'],
    warranty: '24 months TP-Link warranty',
    art: 'router',
    added: '2026-02-01',
    rank: 70,
    keywords: 'tp link tl mr6400 4g lte router sim',
  },
  {
    slug: 'tp-link-tl-sg1008d',
    name: 'TP-Link TL-SG1008D 8-Port Gigabit Switch',
    brand: 'tp-link',
    category: 'networking',
    price: 2799,
    condition: 'new',
    stock: 25,
    tagline: 'More wired ports for the office in one box.',
    highlights: ['8 Gigabit ports', 'Plug and play', 'Energy-efficient'],
    description: 'A simple unmanaged switch that adds eight Gigabit Ethernet ports for desktops, printers and CCTV.',
    specs: [
      ['Ports', '8 × 10/100/1000Mbps'],
      ['Type', 'Unmanaged, desktop'],
    ],
    inBox: ['Switch', 'Power adapter'],
    warranty: '24 months TP-Link warranty',
    art: 'switch',
    added: '2026-02-01',
    rank: 54,
    keywords: 'tp link tl sg1008d network switch',
  },
];

export const accessories: Product[] = [
  {
    slug: 'anker-powercore-20k',
    name: 'Anker PowerCore Essential 20,000mAh',
    brand: 'anker',
    category: 'accessories',
    price: 6499,
    condition: 'new',
    stock: 20,
    tagline: 'Several phone charges through any power cut.',
    highlights: ['20,000mAh capacity', 'USB‑C in/out', 'Anker PowerIQ fast charging'],
    description: 'A trusted high-capacity power bank that charges most phones four or more times — the load-shedding essential.',
    specs: [
      ['Capacity', '20,000mAh'],
      ['Ports', 'USB‑C · USB‑A'],
      ['Charging', 'PowerIQ'],
    ],
    inBox: ['Power bank', 'USB‑C cable', 'Travel pouch'],
    warranty: '18 months Anker warranty',
    art: 'powerbank',
    badges: ['pick'],
    added: '2026-01-10',
    rank: 83,
    keywords: 'anker power bank 20000mah powerbank',
  },
  {
    slug: 'oraimo-20000mah-power-bank',
    name: 'Oraimo 20,000mAh Power Bank',
    brand: 'oraimo',
    category: 'accessories',
    price: 2999,
    condition: 'new',
    stock: 35,
    tagline: 'Reliable backup power for less than KES 3K.',
    highlights: ['20,000mAh capacity', 'Dual USB output', 'LED power indicator'],
    description: 'A dependable everyday power bank from Oraimo with two outputs to charge a phone and earbuds at once.',
    specs: [
      ['Capacity', '20,000mAh'],
      ['Ports', '2 × USB‑A out · USB‑C / micro-USB in'],
    ],
    inBox: ['Power bank', 'Charging cable'],
    warranty: '12 months Oraimo warranty',
    art: 'powerbank',
    added: '2026-01-10',
    rank: 81,
    keywords: 'oraimo power bank 20000mah cheap',
  },
  {
    slug: 'apple-20w-usb-c-adapter',
    name: 'Apple 20W USB‑C Power Adapter (UK plug)',
    brand: 'apple',
    category: 'accessories',
    price: 3499,
    condition: 'new',
    stock: 30,
    tagline: 'The original fast charger for iPhone and iPad.',
    highlights: ['Genuine Apple adapter', 'Fast-charges iPhone to 50% in ~30 min', 'Kenyan three-pin (Type G) plug'],
    description: 'Genuine Apple 20W USB‑C adapter with the UK three-pin plug used in Kenya. Pair with a USB‑C cable for fast charging.',
    specs: [
      ['Output', '20W USB‑C PD'],
      ['Plug', 'Type G (UK three-pin)'],
    ],
    inBox: ['Power adapter'],
    warranty: '12 months Apple warranty',
    art: 'charger',
    added: '2026-01-10',
    rank: 77,
    keywords: 'apple 20w charger usb c adapter original',
  },
  {
    slug: 'samsung-25w-super-fast-charger',
    name: 'Samsung 25W Super Fast Charger',
    brand: 'samsung',
    category: 'accessories',
    price: 2499,
    condition: 'new',
    stock: 30,
    tagline: 'Super Fast Charging for Galaxy phones, the original way.',
    highlights: ['25W Super Fast Charging', 'USB‑C output', 'Type G UK plug'],
    description: 'The genuine Samsung 25W USB‑C charger for Super Fast Charging on supported Galaxy phones and tablets.',
    specs: [
      ['Output', '25W USB‑C PD PPS'],
      ['Plug', 'Type G (UK three-pin)'],
    ],
    inBox: ['Charger', 'USB‑C to USB‑C cable'],
    warranty: '12 months Samsung warranty',
    art: 'charger',
    added: '2026-01-10',
    rank: 74,
    keywords: 'samsung 25w charger original fast',
  },
  {
    slug: 'samsung-t7-1tb-ssd',
    name: 'Samsung T7 Portable SSD 1TB',
    brand: 'samsung',
    category: 'accessories',
    price: 13999,
    compareAt: 15999,
    condition: 'new',
    stock: 8,
    tagline: 'Pocket-sized, fast backup for photos, video and work.',
    highlights: ['Up to 1,050MB/s transfer', 'Shock-resistant aluminium', 'USB‑C with cables for USB‑A'],
    description: 'Samsung T7 is a credit-card-sized SSD that moves files many times faster than a hard drive — perfect for editors and offices.',
    specs: [
      ['Capacity', '1TB'],
      ['Speed', 'Up to 1,050MB/s read'],
      ['Interface', 'USB 3.2 Gen 2 (USB‑C)'],
    ],
    inBox: ['SSD', 'USB‑C to C cable', 'USB‑C to A cable'],
    warranty: '36 months Samsung warranty',
    colours: [
      { name: 'Titan Gray', hex: '#5b5d61' },
      { name: 'Indigo Blue', hex: '#2f4a7a' },
    ],
    art: 'ssd',
    badges: ['deal'],
    added: '2026-01-10',
    rank: 66,
    keywords: 'samsung t7 ssd 1tb external storage',
  },
  {
    slug: 'sandisk-ultra-128gb-microsd',
    name: 'SanDisk Ultra 128GB microSD',
    brand: 'sandisk',
    category: 'accessories',
    price: 1499,
    condition: 'new',
    stock: 50,
    tagline: 'More room for photos, music and WhatsApp media.',
    highlights: ['128GB capacity', 'Up to 140MB/s read', 'A1 rated for apps'],
    description: 'Genuine SanDisk Ultra microSD with SD adapter — for phones, tablets, dashcams and CCTV.',
    specs: [
      ['Capacity', '128GB'],
      ['Speed', 'Up to 140MB/s read · Class 10 · U1 · A1'],
    ],
    inBox: ['microSD card', 'SD adapter'],
    warranty: '10 years SanDisk limited warranty',
    art: 'card',
    added: '2026-01-10',
    rank: 70,
    keywords: 'sandisk ultra 128gb memory card microsd',
  },
  {
    slug: 'logitech-mx-master-3s',
    name: 'Logitech MX Master 3S',
    brand: 'logitech',
    category: 'accessories',
    price: 14999,
    condition: 'new',
    stock: 6,
    tagline: 'The mouse professionals swear by — now quiet clicks.',
    highlights: ['8K DPI tracks on glass', 'Quiet clicks', 'MagSpeed electromagnetic scroll'],
    description: 'MX Master 3S is a sculpted productivity mouse with quiet clicks, a fast MagSpeed wheel and multi-device switching.',
    specs: [
      ['Sensor', '8,000 DPI Darkfield'],
      ['Connectivity', 'Bluetooth · Logi Bolt'],
      ['Battery', 'Up to 70 days · USB‑C'],
    ],
    inBox: ['Mouse', 'Logi Bolt receiver', 'USB‑C cable'],
    warranty: '12 months Logitech warranty',
    colours: [
      { name: 'Graphite', hex: '#3b3d40' },
      { name: 'Pale Grey', hex: '#d6d4cf' },
    ],
    art: 'mouse',
    added: '2026-01-10',
    rank: 58,
    keywords: 'logitech mx master 3s mouse',
  },
  {
    slug: 'logitech-m185-wireless-mouse',
    name: 'Logitech M185 Wireless Mouse',
    brand: 'logitech',
    category: 'accessories',
    price: 1499,
    condition: 'new',
    stock: 40,
    tagline: 'Plug in the receiver and go.',
    highlights: ['Plug-and-play receiver', '12-month battery life', 'Comfortable for either hand'],
    description: 'A dependable compact wireless mouse with a tiny receiver and a battery that lasts about a year.',
    specs: [
      ['Connectivity', '2.4GHz USB receiver'],
      ['Battery', '1 × AA (included)'],
    ],
    inBox: ['Mouse', 'Receiver', 'AA battery'],
    warranty: '12 months Logitech warranty',
    art: 'mouse',
    added: '2026-01-10',
    rank: 62,
    keywords: 'logitech m185 wireless mouse cheap',
  },
  {
    slug: 'logitech-k380-keyboard',
    name: 'Logitech K380 Multi-Device Keyboard',
    brand: 'logitech',
    category: 'accessories',
    price: 5499,
    condition: 'new',
    stock: 12,
    tagline: 'Type on your laptop, tablet and phone from one keyboard.',
    highlights: ['Switch between 3 devices', 'Up to 24 months battery', 'Compact and quiet'],
    description: 'K380 pairs with three devices — laptop, tablet and phone — and switches between them with one key.',
    specs: [
      ['Connectivity', 'Bluetooth · 3 devices'],
      ['Battery', '2 × AAA (included)'],
    ],
    inBox: ['Keyboard', '2 × AAA batteries'],
    warranty: '12 months Logitech warranty',
    colours: [
      { name: 'Graphite', hex: '#3b3d40' },
      { name: 'Off-white', hex: '#ece9e1' },
    ],
    art: 'keyboard',
    added: '2026-01-10',
    rank: 57,
    keywords: 'logitech k380 bluetooth keyboard',
  },
];
