import type { Product } from '../types';

// Prices are launch placeholders in KES — replace with live stock prices before going public.
export const phones: Product[] = [
  {
    slug: 'iphone-17-pro-max',
    name: 'iPhone 17 Pro Max',
    brand: 'apple',
    category: 'phones',
    price: 219999,
    condition: 'new',
    stock: 4,
    tagline: 'The biggest iPhone screen and the longest battery life, in forged aluminium.',
    highlights: ['6.9" ProMotion display up to 120Hz', 'A19 Pro chip with Apple Intelligence', 'Triple 48MP Fusion camera system'],
    description:
      'Apple’s top iPhone with a 6.9-inch Super Retina XDR display, the A19 Pro chip and a triple 48MP camera system with long-range telephoto. Built from aluminium with a Ceramic Shield front, it is the iPhone for people who shoot, edit and work from their phone.',
    specs: [
      ['Display', '6.9" Super Retina XDR, ProMotion up to 120Hz, Always-On'],
      ['Chip', 'A19 Pro'],
      ['Storage', '256GB'],
      ['Rear camera', '48MP Fusion main · 48MP ultra wide · 48MP telephoto'],
      ['Front camera', '18MP Center Stage'],
      ['Connector', 'USB‑C'],
      ['Network', '5G · Dual SIM (nano + eSIM)'],
      ['Water resistance', 'IP68'],
    ],
    inBox: ['iPhone 17 Pro Max', 'USB‑C charge cable (1 m)'],
    warranty: '12 months Apple warranty',
    colours: [
      { name: 'Cosmic Orange', hex: '#c8662e' },
      { name: 'Deep Blue', hex: '#2b3a55' },
      { name: 'Silver', hex: '#d9d9d6' },
    ],
    options: { label: 'Storage', values: [{ name: '256GB' }, { name: '512GB', delta: 32000 }, { name: '1TB', delta: 64000 }] },
    art: 'phone',
    badges: ['new'],
    added: '2026-09-26',
    rank: 98,
    keywords: 'apple iphone 17 pro max promax ip17',
  },
  {
    slug: 'iphone-17',
    name: 'iPhone 17',
    brand: 'apple',
    category: 'phones',
    price: 139999,
    condition: 'new',
    stock: 7,
    tagline: 'ProMotion comes to the standard iPhone, with double the starting storage.',
    highlights: ['6.3" ProMotion display up to 120Hz', '48MP Dual Fusion camera', '256GB storage as standard'],
    description:
      'iPhone 17 brings the smooth ProMotion display to the standard model for the first time, with a 48MP Dual Fusion camera, an 18MP Center Stage front camera and 256GB of storage to start.',
    specs: [
      ['Display', '6.3" Super Retina XDR, ProMotion up to 120Hz'],
      ['Chip', 'A19'],
      ['Storage', '256GB'],
      ['Rear camera', '48MP Fusion main · 48MP Fusion ultra wide'],
      ['Front camera', '18MP Center Stage'],
      ['Connector', 'USB‑C'],
      ['Network', '5G · Dual SIM (nano + eSIM)'],
      ['Water resistance', 'IP68'],
    ],
    inBox: ['iPhone 17', 'USB‑C charge cable (1 m)'],
    warranty: '12 months Apple warranty',
    colours: [
      { name: 'Black', hex: '#1d1d1f' },
      { name: 'Lavender', hex: '#c9bfe0' },
      { name: 'Sage', hex: '#b7c3a7' },
      { name: 'Mist Blue', hex: '#a9bfd6' },
    ],
    options: { label: 'Storage', values: [{ name: '256GB' }, { name: '512GB', delta: 32000 }] },
    art: 'phone',
    badges: ['new'],
    added: '2026-09-26',
    rank: 95,
    keywords: 'apple iphone 17 ip17',
  },
  {
    slug: 'iphone-16',
    name: 'iPhone 16',
    brand: 'apple',
    category: 'phones',
    price: 109999,
    compareAt: 119999,
    condition: 'new',
    stock: 6,
    tagline: 'Camera Control, A18 and Apple Intelligence at a lower price.',
    highlights: ['6.1" Super Retina XDR display', 'Camera Control button', '48MP Fusion camera'],
    description:
      'iPhone 16 brings the A18 chip, the Camera Control button and a 48MP Fusion camera with 2x optical-quality zoom. A smart buy now that iPhone 17 is out.',
    specs: [
      ['Display', '6.1" Super Retina XDR OLED'],
      ['Chip', 'A18'],
      ['Storage', '128GB'],
      ['Rear camera', '48MP Fusion · 12MP ultra wide'],
      ['Front camera', '12MP TrueDepth'],
      ['Connector', 'USB‑C'],
      ['Network', '5G · Dual SIM (nano + eSIM)'],
      ['Water resistance', 'IP68'],
    ],
    inBox: ['iPhone 16', 'USB‑C charge cable (1 m)'],
    warranty: '12 months Apple warranty',
    colours: [
      { name: 'Black', hex: '#1d1d1f' },
      { name: 'Ultramarine', hex: '#5a6fd6' },
      { name: 'Teal', hex: '#8fbfb5' },
      { name: 'Pink', hex: '#efc4d2' },
    ],
    options: { label: 'Storage', values: [{ name: '128GB' }, { name: '256GB', delta: 15000 }] },
    art: 'phone',
    badges: ['deal'],
    added: '2026-05-10',
    rank: 90,
    keywords: 'apple iphone 16 ip16',
  },
  {
    slug: 'iphone-15-128gb',
    name: 'iPhone 15 128GB',
    brand: 'apple',
    category: 'phones',
    price: 92999,
    condition: 'new',
    stock: 5,
    tagline: 'Dynamic Island, a 48MP camera and USB‑C — the sensible iPhone.',
    highlights: ['6.1" Super Retina XDR display', '48MP main camera', 'USB‑C charging'],
    description:
      'iPhone 15 brought Dynamic Island, a 48MP main camera and USB‑C to the standard iPhone. Still an excellent everyday phone with years of iOS updates ahead.',
    specs: [
      ['Display', '6.1" Super Retina XDR OLED'],
      ['Chip', 'A16 Bionic'],
      ['Storage', '128GB'],
      ['Rear camera', '48MP main · 12MP ultra wide'],
      ['Connector', 'USB‑C'],
      ['Network', '5G · Dual SIM (nano + eSIM)'],
    ],
    inBox: ['iPhone 15', 'USB‑C charge cable (1 m)'],
    warranty: '12 months Apple warranty',
    colours: [
      { name: 'Black', hex: '#2b2d2f' },
      { name: 'Blue', hex: '#c9d6df' },
      { name: 'Green', hex: '#d3dfcb' },
    ],
    art: 'phone',
    added: '2026-03-02',
    rank: 70,
    keywords: 'apple iphone 15 ip15',
  },
  {
    slug: 'samsung-galaxy-s25-ultra',
    name: 'Samsung Galaxy S25 Ultra',
    brand: 'samsung',
    category: 'phones',
    price: 164999,
    compareAt: 179999,
    condition: 'new',
    stock: 5,
    tagline: 'A titanium flagship with a built-in S Pen and a 200MP camera.',
    highlights: ['6.9" QHD+ Dynamic AMOLED 2X, 120Hz', 'Snapdragon 8 Elite for Galaxy', '200MP camera with 5x optical zoom'],
    description:
      'Galaxy S25 Ultra pairs the Snapdragon 8 Elite for Galaxy with a 6.9-inch QHD+ display, a built-in S Pen and a 200MP main camera. Galaxy AI tools like Circle to Search and Live Translate are built in.',
    specs: [
      ['Display', '6.9" QHD+ Dynamic AMOLED 2X, 1–120Hz'],
      ['Processor', 'Snapdragon 8 Elite for Galaxy'],
      ['Memory', '12GB RAM'],
      ['Storage', '256GB'],
      ['Rear camera', '200MP main · 50MP ultra wide · 50MP 5x · 10MP 3x'],
      ['Battery', '5,000mAh · 45W wired charging'],
      ['S Pen', 'Built in'],
      ['Water resistance', 'IP68'],
    ],
    inBox: ['Galaxy S25 Ultra', 'S Pen', 'USB‑C cable', 'SIM ejection pin'],
    warranty: '12 months Samsung warranty',
    colours: [
      { name: 'Titanium Silverblue', hex: '#8fa0b5' },
      { name: 'Titanium Black', hex: '#2d2f31' },
      { name: 'Titanium Gray', hex: '#8e8b85' },
    ],
    options: { label: 'Storage', values: [{ name: '256GB' }, { name: '512GB', delta: 20000 }] },
    art: 'phone',
    badges: ['deal'],
    added: '2026-02-15',
    rank: 94,
    keywords: 'samsung galaxy s25 ultra s pen',
  },
  {
    slug: 'samsung-galaxy-s25',
    name: 'Samsung Galaxy S25',
    brand: 'samsung',
    category: 'phones',
    price: 104999,
    condition: 'new',
    stock: 6,
    tagline: 'Flagship power in a compact 6.2" phone.',
    highlights: ['6.2" FHD+ Dynamic AMOLED 2X, 120Hz', 'Snapdragon 8 Elite for Galaxy', '7 years of OS and security updates'],
    description:
      'Galaxy S25 fits flagship performance and Galaxy AI into a phone you can use one-handed, with a 50MP triple camera and seven years of updates.',
    specs: [
      ['Display', '6.2" FHD+ Dynamic AMOLED 2X, 120Hz'],
      ['Processor', 'Snapdragon 8 Elite for Galaxy'],
      ['Memory', '12GB RAM'],
      ['Storage', '256GB'],
      ['Rear camera', '50MP main · 12MP ultra wide · 10MP 3x telephoto'],
      ['Battery', '4,000mAh · 25W wired charging'],
      ['Water resistance', 'IP68'],
    ],
    inBox: ['Galaxy S25', 'USB‑C cable', 'SIM ejection pin'],
    warranty: '12 months Samsung warranty',
    colours: [
      { name: 'Navy', hex: '#2c3a55' },
      { name: 'Icyblue', hex: '#c6d6e3' },
      { name: 'Mint', hex: '#c9e0d1' },
    ],
    art: 'phone',
    added: '2026-02-15',
    rank: 80,
    keywords: 'samsung galaxy s25',
  },
  {
    slug: 'samsung-galaxy-a56-5g',
    name: 'Samsung Galaxy A56 5G',
    brand: 'samsung',
    category: 'phones',
    price: 52999,
    condition: 'new',
    stock: 12,
    tagline: 'Premium feel, 5G and six years of updates for the mid-range.',
    highlights: ['6.7" Super AMOLED, 120Hz', '50MP camera with Nightography', '5,000mAh battery · 45W charging'],
    description:
      'Galaxy A56 5G brings a metal frame, a bright 6.7-inch Super AMOLED screen and Awesome Intelligence features to the mid-range, with six generations of Android updates.',
    specs: [
      ['Display', '6.7" FHD+ Super AMOLED, 120Hz'],
      ['Processor', 'Exynos 1580'],
      ['Memory', '8GB RAM'],
      ['Storage', '256GB'],
      ['Rear camera', '50MP main · 12MP ultra wide · 5MP macro'],
      ['Battery', '5,000mAh · 45W charging'],
      ['Water resistance', 'IP67'],
    ],
    inBox: ['Galaxy A56 5G', 'USB‑C cable', 'SIM ejection pin'],
    warranty: '12 months Samsung warranty',
    colours: [
      { name: 'Awesome Graphite', hex: '#3b3d40' },
      { name: 'Awesome Olive', hex: '#9aa37f' },
      { name: 'Awesome Pink', hex: '#e9c9cf' },
    ],
    art: 'phone',
    badges: ['pick'],
    added: '2026-04-01',
    rank: 88,
    keywords: 'samsung galaxy a56 5g',
  },
  {
    slug: 'samsung-galaxy-a16',
    name: 'Samsung Galaxy A16',
    brand: 'samsung',
    category: 'phones',
    price: 19499,
    compareAt: 21999,
    condition: 'new',
    stock: 25,
    tagline: 'Six years of updates on a budget — a rare promise at this price.',
    highlights: ['6.7" Super AMOLED display', '50MP triple camera', '6 generations of Android updates'],
    description:
      'Galaxy A16 is the budget phone that keeps going: a 6.7-inch Super AMOLED screen, a 5,000mAh battery and six generations of Android OS updates.',
    specs: [
      ['Display', '6.7" FHD+ Super AMOLED, 90Hz'],
      ['Memory', '4GB RAM'],
      ['Storage', '128GB · microSD up to 1.5TB'],
      ['Rear camera', '50MP main · 5MP ultra wide · 2MP macro'],
      ['Battery', '5,000mAh · 25W charging'],
      ['Network', '4G · Dual SIM'],
    ],
    inBox: ['Galaxy A16', 'USB‑C cable', 'SIM ejection pin'],
    warranty: '12 months Samsung warranty',
    colours: [
      { name: 'Black', hex: '#2a2b2e' },
      { name: 'Light Green', hex: '#cfe0cf' },
      { name: 'Gray', hex: '#a7a9ac' },
    ],
    art: 'phone',
    badges: ['deal'],
    added: '2026-01-20',
    rank: 92,
    keywords: 'samsung galaxy a16 budget',
  },
  {
    slug: 'samsung-galaxy-a06',
    name: 'Samsung Galaxy A06',
    brand: 'samsung',
    category: 'phones',
    price: 13499,
    condition: 'new',
    stock: 30,
    tagline: 'A big screen, a big battery and the Samsung name for under KES 15K.',
    highlights: ['6.7" HD+ display', '50MP main camera', '5,000mAh battery'],
    description: 'Galaxy A06 is a dependable first smartphone or second line: a large 6.7-inch screen, 50MP camera and a battery that lasts all day.',
    specs: [
      ['Display', '6.7" HD+ PLS LCD, 90Hz'],
      ['Processor', 'MediaTek Helio G85'],
      ['Memory', '4GB RAM'],
      ['Storage', '64GB · microSD supported'],
      ['Rear camera', '50MP main · 2MP depth'],
      ['Battery', '5,000mAh · 25W charging'],
    ],
    inBox: ['Galaxy A06', 'USB‑C cable', 'SIM ejection pin'],
    warranty: '12 months Samsung warranty',
    colours: [
      { name: 'Black', hex: '#2a2b2e' },
      { name: 'Light Blue', hex: '#c7d8ea' },
    ],
    art: 'phone',
    added: '2026-01-20',
    rank: 72,
    keywords: 'samsung galaxy a06 cheap',
  },
  {
    slug: 'google-pixel-9a',
    name: 'Google Pixel 9a',
    brand: 'google',
    category: 'phones',
    price: 62999,
    condition: 'new',
    stock: 3,
    tagline: 'Google’s best camera software and 7 years of updates, at a mid-range price.',
    highlights: ['6.3" Actua display, up to 120Hz', 'Google Tensor G4', '7 years of OS and security updates'],
    description: 'Pixel 9a brings Google’s photo processing, Gemini and seven years of updates to a clean, flat design with IP68 protection.',
    specs: [
      ['Display', '6.3" Actua pOLED, 60–120Hz'],
      ['Processor', 'Google Tensor G4'],
      ['Memory', '8GB RAM'],
      ['Storage', '128GB'],
      ['Rear camera', '48MP main · 13MP ultra wide'],
      ['Battery', '5,100mAh'],
      ['Water resistance', 'IP68'],
    ],
    inBox: ['Pixel 9a', 'USB‑C to USB‑C cable', 'Quick Switch adapter', 'SIM tool'],
    warranty: '12 months Steff Store warranty',
    colours: [
      { name: 'Obsidian', hex: '#2b2c2e' },
      { name: 'Porcelain', hex: '#ece7df' },
      { name: 'Iris', hex: '#9da3d6' },
    ],
    art: 'phone',
    added: '2026-04-22',
    rank: 66,
    keywords: 'google pixel 9a',
  },
  {
    slug: 'redmi-note-14-pro-5g',
    name: 'Redmi Note 14 Pro 5G',
    brand: 'xiaomi',
    category: 'phones',
    price: 39999,
    condition: 'new',
    stock: 9,
    tagline: 'A 200MP camera and IP68 toughness for under KES 40K.',
    highlights: ['6.67" 1.5K AMOLED, 120Hz', '200MP main camera with OIS', 'IP68 dust and water resistance'],
    description: 'Redmi Note 14 Pro 5G punches above its price with a 1.5K AMOLED display, a 200MP stabilised camera and IP68 protection.',
    specs: [
      ['Display', '6.67" 1.5K AMOLED, 120Hz'],
      ['Processor', 'MediaTek Dimensity 7300-Ultra'],
      ['Memory', '8GB RAM'],
      ['Storage', '256GB'],
      ['Rear camera', '200MP main (OIS) · 8MP ultra wide · 2MP macro'],
      ['Battery', '5,110mAh · 45W HyperCharge'],
      ['Water resistance', 'IP68'],
    ],
    inBox: ['Redmi Note 14 Pro 5G', '45W charger', 'USB‑C cable', 'Protective case', 'SIM tool'],
    warranty: '12 months Xiaomi warranty',
    colours: [
      { name: 'Midnight Black', hex: '#25262a' },
      { name: 'Ocean Blue', hex: '#4c6f9a' },
      { name: 'Lavender Purple', hex: '#b7a7d6' },
    ],
    art: 'phone',
    badges: ['pick'],
    added: '2026-03-12',
    rank: 84,
    keywords: 'xiaomi redmi note 14 pro 5g',
  },
  {
    slug: 'redmi-14c',
    name: 'Redmi 14C',
    brand: 'xiaomi',
    category: 'phones',
    price: 14999,
    condition: 'new',
    stock: 20,
    tagline: 'A huge 6.88" screen and a charger in the box.',
    highlights: ['6.88" display, 120Hz', '50MP AI dual camera', '5,160mAh battery'],
    description: 'Redmi 14C gives you a very large, smooth screen and a long-lasting battery, with the charger included in the box.',
    specs: [
      ['Display', '6.88" HD+, 120Hz'],
      ['Processor', 'MediaTek Helio G81-Ultra'],
      ['Memory', '4GB RAM'],
      ['Storage', '128GB'],
      ['Rear camera', '50MP main'],
      ['Battery', '5,160mAh · 18W charging'],
    ],
    inBox: ['Redmi 14C', 'Charger', 'USB‑C cable', 'SIM tool'],
    warranty: '12 months Xiaomi warranty',
    colours: [
      { name: 'Midnight Black', hex: '#25262a' },
      { name: 'Sage Green', hex: '#b8c8b0' },
      { name: 'Dreamy Purple', hex: '#c9b8e0' },
    ],
    art: 'phone',
    added: '2026-02-01',
    rank: 68,
    keywords: 'xiaomi redmi 14c',
  },
  {
    slug: 'tecno-camon-30',
    name: 'Tecno Camon 30',
    brand: 'tecno',
    category: 'phones',
    price: 27999,
    compareAt: 31499,
    condition: 'new',
    stock: 14,
    tagline: 'A portrait camera made for Kenyan skin tones, and 70W charging.',
    highlights: ['6.78" AMOLED, 120Hz', '50MP main camera with OIS', '5,000mAh battery · 70W fast charge'],
    description: 'Tecno Camon 30 is built around the camera: a stabilised 50MP sensor, a 50MP selfie camera and portrait tuning that gets skin tones right.',
    specs: [
      ['Display', '6.78" FHD+ AMOLED, 120Hz'],
      ['Processor', 'MediaTek Helio G99 Ultimate'],
      ['Memory', '8GB RAM (+ extended)'],
      ['Storage', '256GB'],
      ['Rear camera', '50MP main (OIS) · 2MP depth'],
      ['Front camera', '50MP'],
      ['Battery', '5,000mAh · 70W charging'],
    ],
    inBox: ['Tecno Camon 30', '70W charger', 'USB‑C cable', 'Case', 'SIM tool'],
    warranty: '12 months Tecno warranty',
    colours: [
      { name: 'Basaltic Dark', hex: '#2b2c2f' },
      { name: 'Uyuni Salt White', hex: '#ecebe6' },
    ],
    art: 'phone',
    badges: ['deal'],
    added: '2026-01-10',
    rank: 86,
    keywords: 'tecno camon 30',
  },
  {
    slug: 'tecno-spark-20-pro-plus',
    name: 'Tecno Spark 20 Pro+',
    brand: 'tecno',
    category: 'phones',
    price: 22999,
    condition: 'new',
    stock: 16,
    tagline: 'A curved AMOLED screen and a 108MP camera on a Spark budget.',
    highlights: ['6.78" curved AMOLED, 120Hz', '108MP main camera', '256GB storage'],
    description: 'Spark 20 Pro+ brings a curved AMOLED display and a 108MP camera to Tecno’s value range, with plenty of storage for photos and apps.',
    specs: [
      ['Display', '6.78" FHD+ curved AMOLED, 120Hz'],
      ['Processor', 'MediaTek Helio G99'],
      ['Memory', '8GB RAM'],
      ['Storage', '256GB'],
      ['Rear camera', '108MP main · 2MP depth'],
      ['Battery', '5,000mAh · 33W charging'],
    ],
    inBox: ['Tecno Spark 20 Pro+', 'Charger', 'USB‑C cable', 'Case', 'SIM tool'],
    warranty: '12 months Tecno warranty',
    colours: [
      { name: 'Temporal Orbits', hex: '#3c4a3f' },
      { name: 'Lunar Frost', hex: '#e5e4df' },
    ],
    art: 'phone',
    added: '2026-01-10',
    rank: 74,
    keywords: 'tecno spark 20 pro plus',
  },
  {
    slug: 'infinix-note-40-pro',
    name: 'Infinix Note 40 Pro',
    brand: 'infinix',
    category: 'phones',
    price: 29999,
    condition: 'new',
    stock: 10,
    tagline: 'Wireless MagCharge and 70W wired charging in a slim curved phone.',
    highlights: ['6.78" curved AMOLED, 120Hz', '108MP main camera with OIS', '70W wired · 20W wireless MagCharge'],
    description: 'Infinix Note 40 Pro is the fast-charging specialist: 70W wired and 20W magnetic wireless charging, a curved AMOLED screen and a 108MP camera.',
    specs: [
      ['Display', '6.78" FHD+ curved AMOLED, 120Hz'],
      ['Processor', 'MediaTek Helio G99 Ultimate'],
      ['Memory', '8GB RAM'],
      ['Storage', '256GB'],
      ['Rear camera', '108MP main (OIS) · 2MP macro · 2MP depth'],
      ['Battery', '5,000mAh · 70W wired · 20W wireless'],
    ],
    inBox: ['Infinix Note 40 Pro', '70W charger', 'USB‑C cable', 'Case', 'SIM tool'],
    warranty: '12 months Infinix warranty',
    colours: [
      { name: 'Obsidian Black', hex: '#232427' },
      { name: 'Vintage Green', hex: '#5b6e55' },
      { name: 'Titan Gold', hex: '#c8b48a' },
    ],
    art: 'phone',
    added: '2026-02-08',
    rank: 76,
    keywords: 'infinix note 40 pro',
  },
  {
    slug: 'infinix-hot-40i',
    name: 'Infinix Hot 40i',
    brand: 'infinix',
    category: 'phones',
    price: 13999,
    condition: 'new',
    stock: 22,
    tagline: 'Big storage for the price, with a 32MP selfie camera.',
    highlights: ['6.56" display, 90Hz', '50MP main · 32MP selfie', '128GB storage'],
    description: 'Hot 40i is a strong budget pick with 128GB of storage, a 32MP selfie camera with front flash, and a 5,000mAh battery.',
    specs: [
      ['Display', '6.56" HD+, 90Hz'],
      ['Processor', 'Unisoc T606'],
      ['Memory', '4GB RAM (+ extended)'],
      ['Storage', '128GB'],
      ['Rear camera', '50MP main'],
      ['Front camera', '32MP with flash'],
      ['Battery', '5,000mAh · 18W charging'],
    ],
    inBox: ['Infinix Hot 40i', 'Charger', 'USB‑C cable', 'Case', 'SIM tool'],
    warranty: '12 months Infinix warranty',
    colours: [
      { name: 'Starlit Black', hex: '#232427' },
      { name: 'Palm Blue', hex: '#7fa6c9' },
    ],
    art: 'phone',
    added: '2026-01-05',
    rank: 64,
    keywords: 'infinix hot 40i',
  },
];
